### ISSUE TITLE
luaotfload-dev (branch harfnode-dev) lost ability to properly display some Tibetan compounds

### ISSUE THREAD

**Issue by norbusan** [latex3/luaotfload#103]
All tests are done with
```
$ luahblatex --credits
This is LuaHBTeX, Version 1.11.1 (TeX Live 2020/dev)

The LuaTeX team is Hans Hagen, Hartmut Henkel, Taco Hoekwater, Luigi Scarso.

LuaHBTeX merges and builds upon (parts of) the code from these projects:

tex       : Donald Knuth
etex      : Peter Breitenlohner, Phil Taylor and friends
omega     : John Plaice and Yannis Haralambous
aleph     : Giuseppe Bilotta
pdftex    : Han The Thanh and friends
kpathsea  : Karl Berry, Olaf Weber and others
lua       : Roberto Ierusalimschy, Waldemar Celes and Luiz Henrique de Figueiredo
metapost  : John Hobby, Taco Hoekwater, Luigi Scarso, Hans Hagen and friends
pplib     : Paweł Jackowski
fontforge : George Williams (partial)
luajit    : Mike Pall (used in LuajitTeX)

Compiled with libharfbuzz 2.6.2; using 2.6.2
Compiled with libpng 1.6.37; using 1.6.37
Compiled with lua version 5.3.5
Compiled with mplib version 2.00
Compiled with zlib 1.2.11; using 1.2.11

Development id: 7195
```
Correct display:
![Screenshot from 2019-10-17 17-17-56](https://user-images.githubusercontent.com/1735589/66990986-2be27200-f102-11e9-90e9-d99c096a238d.png)

Log file for this run: 
[tibetan-test.log](https://github.com/latex3/luaotfload/files/3738130/tibetan-test.log)

With the -dev version installed and formats rebuild:
![Screenshot from 2019-10-17 17-18-11](https://user-images.githubusercontent.com/1735589/66991073-546a6c00-f102-11e9-9331-175ec241cce1.png)

Logfile for the failed run:
[tibetan-test.log](https://github.com/latex3/luaotfload/files/3738139/tibetan-test.log)

Input file (contains lots of other code and examples, though):
[tibetan-test.txt](https://github.com/latex3/luaotfload/files/3738144/tibetan-test.txt)

**Comment by zauguin** [comment]
Tracked upstream as https://github.com/harfbuzz/harfbuzz/issues/2037.

**Comment by zauguin** [comment]
@norbusan Can you check if this is fixed in TeX Live 2021?

**Comment by norbusan** [comment]
Yes, it seems to be fixed for most fonts. I just run the lualatex from TL 2021 pretest 
```
$ lualatex tibetan-test.tex 
This is LuaHBTeX, Version 1.13.0 (TeX Live 2021) 
 restricted system commands enabled.
(./tibetan-test.tex
LaTeX2e <2020-10-01> patch level 4
 L3 programming layer <2021-02-18>
```
and got this:
![image](https://user-images.githubusercontent.com/1735589/109371013-37dd6700-78e6-11eb-8e23-b12c3f101c16.png)
where the fonts are from left to right: DDC-Uchen, Noto Tibetan Serif, Jomolhari, Yagpo, Qomolangma/

Jomolhari is broken in many more respects, so I guess that can be ignored. Noto provides the best overall quality of layout.
