### ISSUE TITLE
luaotfload-tool: support Lua patterns where appropriate

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/luaotfload#105]
For example it is currently not possible to list all fonts that are related to the different Fira families, instead one needs to know the exact family names and use several calls with `--list`. Nicer would be something like `--list=familyname:fira.*`  (or `Fira.*` see #104)

**Comment by zauguin** [comment]
This is a bit complicated to implement in combination with #104: Basically we would have to parse the pattern and translate it into a pattern of the sanitized name. All to get functionality which is probably not needed in that generality.
@FrankMittelbach So you think it would be enough to restrict this to shell style `*` globbing? So getting all Fira fonts using `--list=familyname:Fira*`?

**Comment by zauguin** [comment]
Since v3.13, shell style `*` globbing is supported.

**Comment by FrankMittelbach** [comment]
thanks, will test
