### ISSUE TITLE
harfnode-dev: same font with node and harf mode in one document

### ISSUE THREAD

**Issue by dohyunkim** [latex3/luaotfload#107]
```latex
\documentclass{article}
\def\hunmin{%
  世솅〮宗조ᇰ御ᅌᅥᆼ〮製졩〮訓훈〮民민正져ᇰ〮音ᅙᅳᆷ
}
\begin{document}
\font\konode={NotoSansCJKKR:mode=node;language=KOR;script=hang} at 14pt
\konode \hunmin

\font\koharf={NotoSansCJKKR:mode=harf;language=KOR;script=hang} at 14pt
\koharf \hunmin

\loggingoutput
\end{document}
```

![image](https://user-images.githubusercontent.com/4328134/67380817-dd334d00-f5c5-11e9-9733-95a0fa0f4fd3.png)

Upon running with luahblatex-dev, the first line is wrong because Hangul Tone Mark (U+302E) comes behind the syllable. This is a well known limitation of `node` mode.

The second line is free from this problem, but is garbled as shown. When the first part which uses `node` mode is commented out, the problem is gone and all is good.

Who is the culprit, luatex engine or luaotfload? Or is it not allowed to mix `node` mode and `harf` mode of a font in one docment?

**Comment by zauguin** [comment]
@dohyunkim I the second line of the following image the right output?

![image](https://user-images.githubusercontent.com/962229/67392988-d09cfd80-f5a1-11e9-8ccf-1b035649e618.png)

**Comment by dohyunkim** [comment]
@zauguin Yes, it's the expected result.

**Comment by zauguin** [comment]
Just an update: I have a fix, but it triggers a IMO LuaTeX bug which terminates LuaTeX when used with a `.ttc` font like NotoSansCJKKR, so I am currently waiting if the LuaTeX team fixed this for the next version or if we have to work-around this.

**Comment by zauguin** [comment]
The branch  `multimode-dev` has the fix which works in current experimental builds of LuaHBTeX (aka. Development id  >= 7222, LuaHBTeX 1.11.2).

It breaks ttc fonts with `mode=harf` in older versions, so I think we shouldn't merge it yet.

**Comment by dohyunkim** [comment]
Confirm that it works quite well now with experimental LuaHBTeX binary.
Thank you very much.

**Comment by zauguin** [comment]
Fixed in `dev`
