### ISSUE TITLE
Fatal error using current dev branch (3.0006-dev) and fontspec

### ISSUE THREAD

**Issue by bgvoisin** [latex3/luaotfload#108]
Take sample2e.tex for example and add in the preamble

`
\usepackage{fontspec}
\if1\directlua{if luaotfload.harfbuzz then tex.print("2") else tex.print("1") end}
  \setmainfont{lmroman10-regular.otf}
\else
  \setmainfont{lmroman10-regular.otf}[RawFeature={mode=harf}]
\fi
`

With release luaotfload (v3.00) this works fine, but with the dev version (v3.0006-dev) this gives

`
error:  (linebreak): invalid list tail, probably missing glue
==> Fatal error occurred, no output PDF file produced!
`

This is not specific to Latin Modern, and happens with TeX Gyre Termes and STIX Two for example (the other fonts I tried). I cannot tell whether the problem is with luaotfload or fontspec.

**Comment by u-fischer** [comment]
works fine for me on windows. Which luatex version are you using? And which branch in which state did you use? (version numbers are not always unique here). Is there a log-file?

**Comment by bgvoisin** [comment]
This was on Mac, with luahbtex/luahbtex-dev newly compiled by Norbert retrieved from tlcontrib today, that is

	https://git.texlive.info/tlcontrib/tree/bin/x86_64-darwin

and luaotfload-dev from

	https://github.com/latex3/luaotfload/releases/download/v3.0006-dev/luaotfload-dev.tds.zip

The input file and log-file are attached.

**Comment by u-fischer** [comment]
The release is 10 days old and a lot happened in between.

**Comment by norbusan** [comment]
@bgvoisin @u-fischer I can confirm that with current git checkout of luaotfload the error Bruno reported does not occur anymore.

**Comment by zauguin** [comment]
Fixed in v3.1.
