### ISSUE TITLE
Additional shaper support in HarfBuzz

### ISSUE THREAD

**Issue by zauguin** [latex3/luaotfload#112]
~Graphite2 fonts are broken with `harf`.  This should be fixed and until then the `ot` renderer should be enforced.~ 

Graphite and AAT fonts need proper tests.

**Comment by khaledhosny** [comment]
They worked fine last time I touched this code (I even had a test using Awami Nastaliq font, which uses Graphite tables rather extensively).

**Comment by khaledhosny** [comment]
(The shapers should be transparent to LuaTeX side of things as it is all done by HarfBuzz, so I can’t think of any reason why a specific shaper would be broken unless it is a bug in HarfBuzz or a specific build of it).

**Comment by zauguin** [comment]
@khaledhosny One problem is that non `ot` shapers always set `UNSAFE_TO_BREAK`, so they don't get very good hyphenation in our current implementation.

Also this gave the impression that they don't work at all because this triggered multiple bugs I introduced in the discretionary handling code. I think(hope) they are all fixed now.

The other problem I encountered was probably font specific, my primary test font really needs reshaping after breaking at spaces, so it doesn't work properly with `harf` (this caused discretionary nodes to overprint previous text and similar problems)

So we are back were we started: They should work, but we need good tests.

**Comment by khaledhosny** [comment]
> @khaledhosny One problem is that non `ot` shapers always set `UNSAFE_TO_BREAK`, so they don't get very good hyphenation in our current implementation.

Right, I completely forgot about this.

> Also this gave the impression that they don't work at all because this triggered multiple bugs I introduced in the discretionary handling code. I think(hope) they are all fixed now.

I’m always amazed this code works at all, sorry about the trouble.

> The other problem I encountered was probably font specific, my primary test font really needs reshaping after breaking at spaces, so it doesn't work properly with `harf` (this caused discretionary nodes to overprint previous text and similar problems)

Hmm, the code is supposed to not make any assumptions about this (but I don’t think I actually tested that).

> So we are back were we started: They should work, but we need good tests.

Nice. I was only thinking about Graphite for complex fonts where OpenType is not enough, and they usually are for scripts that don’t need hyphenation, so I didn’t even occur to me to test discretionary handling with them.

**Comment by zauguin** [comment]
> They worked fine last time I touched this code (I even had a test using Awami Nastaliq font, which uses Graphite tables rather extensively).

I just realized that we also had this test and I had made sure that it produces the same result as the old `harf` code, I just wasn't aware that it uses Graphite.

> I’m always amazed this code works at all, sorry about the trouble.

There's nothing to be sorry for, we are very grateful for you contribution!
