### ISSUE TITLE
font color and custom mlist_to_hlist

### ISSUE THREAD

**Issue by h-kitagawa** [latex3/luaotfload#118]
Hello,

luaotfload registers `mlist_to_hlist` callback when `color=...` is specified first in a document. This causes an error when a function is already registered to `mlist_to_hlist` callback, since it is a exclusive one:

```tex
\documentclass{minimal}
\directlua{
  luatexbase.add_to_callback('mlist_to_hlist',
    function (...) return node.mlist_to_hlist(...) end, 'foo')
}
\begin{document}
\font\TEST=file:lmroman10-regular.otf:color=0000FF
\TEST
\end{document}
% Module luatexbase Error: Cannot add second callback to exclusive function
% (luatexbase)             `mlist_to_hlist' on input line 8
% .
```

Although very few packages use `mlist_to_hlist` callback (I found only [nodetree](https://github.com/Josef-Friedrich/nodetree) and [LuaTeX-ja](https://osdn.net/projects/luatex-ja/scm/git/luatexja/)), it would be convenient that there is a callback like 
```
luaotfload.before_mlist_to_hlist_filter: 
  <mlist> head, <string> display_type, <bool> need_penalties
  --> <mlist> newhead
```

**Comment by zauguin** [comment]
This has been added directly in the kernel as part of https://github.com/latex3/latex2e/pull/246 and will be available with the upcoming release. The new callbacks are named `pre_mlist_to_hlist_filter` and `post_mlist_to_hlist_filter` (without `luaotfload.`).
