### ISSUE TITLE
Ignoring unknown font features

### ISSUE THREAD

**Issue by schlcht** [latex3/luaotfload#121]
First off, this is not a bug report but a request for clarification/discussion.

As it stands, luaotfload seems to gracefully ignore unknown font features, eg.:
```
\font\x={Arial:mode=node;script=latn;language=DFLT;nonsense}
```
or even 
```
\font\x={Arial:mode=node;script=latn;language=DFLT;nonsense=meaningless}
```

My question would be whether this is by design and if it will stay that way. For my purposes it would actually be _good_ if it did.

To sketch the background to this question: The `microtype` package allows having different microtypographic settings for the same font in different portions of the document. While when running under pdftex, this is realised with its `\pdfcopyfont` primitive, this is not really an option in luatex (even though it provides the same primitive as `\copyfont`), as OpenType features will be lost (see eg. [here](https://tex.stackexchange.com/questions/338942/cancellation-of-color-fontspec-font-settings-while-defining-microtype-context)). This has been discussed [here](https://mailman.ntg.nl/pipermail/ntg-context/2016/087547.html), and Hans has made clear that he doesn’t consider this a bug, thus it won’t change. His advice was to "just define the font again". However, luatex seems to have difficulties distinguishing two fonts that have been defined under different names but with the same invocation, which leads to problems when applying microtypography. Everything works fine when one adds a feature just for the sake of differentiating the fonts, hence I am planning to go with this solution for the next `microtype` update. But of course I wouldn’t want to have this explode in the future, should the `luaotfload` behaviour towards unknown font features change at some point. Maybe it would make sense to register a dedicated `microtype` feature as a no-op with `luaotfload`?

Here is a minimal example to play with that shows the problems I mentioned. If you change the number in `\MTcontext=2` to `1`, luatex will bail out with "`font has been expanded with different stretch limit`". Fix this by removing one of the `\expandglyphsinfont` lines, and the output will show that the comma is protruded inwards in both paragraphs, while it should be protruding outwards in the first. 

```
\hsize=7cm
\input luaotfload.sty
\adjustspacing=2
\protrudechars=2
\def\x{Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut purus elit, vestibulum ut, placerat ac, adipiscing vitae, felis. }
\font\1={Latin Modern Roman:MTcontext=1}
\font\2={Latin Modern Roman:MTcontext=2} 
\expandglyphsinfont\1 50 50 1
\expandglyphsinfont\2 10 10 1
\rpcode\1`\,=500
\rpcode\2`\,=-500

\1\x\x

\2\x\x
\bye
```
Of course, the ideal solution would be if this were fixed in luatex, but as `microtype` is using the legacy commands, I have my doubts that the luatex team would acknowledge this as a bug. On the other hand, I don’t see any downsides with the solution of using a faux feature.

**Comment by zauguin** [comment]
> As it stands, luaotfload seems to gracefully ignore unknown font features, eg.:
> 
> ```
> \font\x={Arial:mode=node;script=latn;language=DFLT;nonsense}
> ```
> 
> or even
> 
> ```
> \font\x={Arial:mode=node;script=latn;language=DFLT;nonsense=meaningless}
> ```
> 
> My question would be whether this is by design and if it will stay that way. For my purposes it would actually be _good_ if it did.

IMO this is the expected behaviour and I'm currently working on at least one feature which will break otherwise, so undefined font features will always be ignored. But see the caveat below.

> 
> To sketch the background to this question: The `microtype` package allows having different microtypographic settings for the same font in different portions of the document. While when running under pdftex, this is realised with its `\pdfcopyfont` primitive, this is not really an option in luatex (even though it provides the same primitive as `\copyfont`), as OpenType features will be lost (see eg. [here](https://tex.stackexchange.com/questions/338942/cancellation-of-color-fontspec-font-settings-while-defining-microtype-context)). This has been discussed [here](https://mailman.ntg.nl/pipermail/ntg-context/2016/087547.html), and Hans has made clear that he doesn’t consider this a bug, thus it won’t change. His advice was to "just define the font again".

Right, copying fonts is actually quite complicated on a theoretical level with Lua-loaded fonts (it basically ends up with the question of how the Lua table should be copied). We could add a "semi-primitive" which emulates "real" font copying and is bit more efficient, but I think there are better options here.

> However, luatex seems to have difficulties distinguishing two fonts that have been defined under different names but with the same invocation, which leads to problems when applying microtypography. Everything works fine when one adds a feature just for the sake of differentiating the fonts, hence I am planning to go with this solution for the next `microtype` update. But of course I wouldn’t want to have this explode in the future, should the `luaotfload` behaviour towards unknown font features change at some point. Maybe it would make sense to register a dedicated `microtype` feature as a no-op with `luaotfload`?

It's not so much that LuaTeX *can't* differentiate them, it's that they are deduplicated as an optimization... We could change this, but if I recall correctly some code relies on this and just keeps redefining fonts instead of reusing existing names. (Mostly to "rename" the fonts in question)

> 
> Here is a minimal example to play with that shows the problems I mentioned. If you change the number in `\MTcontext=2` to `1`, luatex will bail out with "`font has been expanded with different stretch limit`". Fix this by removing one of the `\expandglyphsinfont` lines, and the output will show that the comma is protruded inwards in both paragraphs, while it should be protruding outwards in the first.
> 
> ```
> \hsize=7cm
> \input luaotfload.sty
> \adjustspacing=2
> \protrudechars=2
> \def\x{Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut purus elit, vestibulum ut, placerat ac, adipiscing vitae, felis. }
> \font\1={Latin Modern Roman:MTcontext=1}
> \font\2={Latin Modern Roman:MTcontext=2} 
> \expandglyphsinfont\1 50 50 1
> \expandglyphsinfont\2 10 10 1
> \rpcode\1`\,=500
> \rpcode\2`\,=-500
> 
> \1\x\x
> 
> \2\x\x
> \bye
> ```
> 
> Of course, the ideal solution would be if this were fixed in luatex, but as `microtype` is using the legacy commands, I have my doubts that the luatex team would acknowledge this as a bug. On the other hand, I don’t see any downsides with the solution of using a faux feature.

The downside is that we assume the font to be immutable after loading, so I fear that similar issues might pop up again. Especially, while I am quite sure that additional unknown features will always be ignored, it might at some point happen that passing unknown features also just returns the same font instead of defining a new one. So I would at least define your fake feature as a feature which does nothing to avoid triggering such optimizations at some point.

Of course, it would be cleaner to actually define "real" new features and set the expansion/protrusion using the new font feature if they are known during font loading anyway. That would require LuaTeX specific code through.

**Comment by u-fischer** [comment]
unicode-math imho uses (small) scaling to reload a font. Would this be an option here too? And would it make sense if unicode-math and microtype use the same method? 

What is with harf-mode. Does the method works with it too? And what impact has this fake features on the font cache and the memory? How many fonts are created in a typical document?

**Comment by schlcht** [comment]
@zauguin wrote:
> So I would at least define your fake feature as a feature which does nothing to avoid triggering such optimizations at some point.

Thanks, that sounds good. 

> Of course, it would be cleaner to actually define "real" new features and set the expansion/protrusion using the new font feature if they are known during font loading anyway. That would require LuaTeX specific code through.

I know, it's been on my agenda for a while to get rid of the legacy commands, but as this would involve lots of changes in latex code (hooking in before font definition time instead of after), lua code (in which I'm not really fluent) and probably also having to keep up with changes in both luatex and luaotfload, I've been shying away from it so far.

@u-fischer wrote:
> unicode-math imho uses (small) scaling to reload a font. Would this be an option here too? 

This was also the previous solution for microtype (before the advent of \pdfcopyfont), but using a fake feature seems much cleaner to me.

> And would it make sense if unicode-math and microtype use the same method?

It would probably be possible for unicode-math to use a fake feature instead of minimal scaling, too. But if you're suggesting that both packages should share a feature to that end, I'd rather keep them separate lest both microtype and unicode-math have to check whether the respective other package has already used that feature. 

> What is with harf-mode. Does the method works with it too? 

I guess so (and haven't found any problems in basic tests). If it is only a no-op feature would it even get to the point of affecting the mode?

> And what impact has this fake features on the font cache and the memory? How many fonts are created in a typical document?

Typical documents would probably only have one extra context, in which all fonts used in its scope would be defined again. As you might be aware microtype checks whether it has already seen a particular font (possibly in a particular context), so my guess would be that the number of font definitions would double at most.

**Comment by zauguin** [comment]
@schlcht
> > Of course, it would be cleaner to actually define "real" new features and set the expansion/protrusion using the new font feature if they are known during font loading anyway. That would require LuaTeX specific code through.
> 
> I know, it's been on my agenda for a while to get rid of the legacy commands, but as this would involve lots of changes in latex code (hooking in before font definition time instead of after), lua code (in which I'm not really fluent) and probably also having to keep up with changes in both luatex and luaotfload, I've been shying away from it so far.

It would certainly require quite some LaTeX changes, but if you give us a list of required features we can implement them in luaotfload and make sure that you have a stable interface there.

By the way, the next luaotfload version will have an expansion feature:

```
\font\lmr"[lmroman10-regular.otf]:expansion=1000 1000 30"
```
will do basically the same as
```
\font\lmr"[lmroman10-regular.otf]"
\expandglyphsinfont\lmr 1000 1000 30
```
without all the font caching issues. (4907e23407c52437cca56966d11d3b4548bba585)
