### ISSUE TITLE
Apparent ToUnicode/cmap/... problems

### ISSUE THREAD

**Issue by krono** [latex3/luaotfload#122]
[If this is not the correct place to report, sorry for the noise]

Using luaotfloat/luatex, it seems that glyphmappings are not created properly.

## MWE
```
\input luaotfload.sty

\font\e=file:EBGaramond-Regular.otf at 12pt
\e beneficial
\font\f=file:FiraSans-Regular.otf at 12pt
\f beneficial
\bye
```

[t.pdf](https://github.com/latex3/luaotfload/files/3887129/t.pdf)
[t.log](https://github.com/latex3/luaotfload/files/3887130/t.log)

```
luatex t.tex
```

## Result
Copying from the resulting PDF (attached) results in
```bene cial bene cial```

The font files seem to have correct names (I found corresponding entries in `luaotfload-tounicode.lua`):
```
$ otfinfo -g $(kpsewhich EBGaramond-Regular.otf) |grep 'f_i'
f_f_i
f_i
$ otfinfo -g $(kpsewhich FiraSans-Regular.otf) |grep 'f_i'
f_f_i
f_i
f_i.sc
```
-----
### Package information for involved packages

```
$ tlmgr info ebgaramond fira luaotfload
package:     ebgaramond
shortdesc:   LaTeX support for EBGaramond fonts
installed:   Yes
revision:    52507
cat-date:    2019-10-22 21:04:50 +0200

package:     fira
shortdesc:   Fira fonts with LaTeX support
installed:   Yes
revision:    52339
cat-date:    2019-10-11 06:57:12 +0200

package:     luaotfload
shortdesc:   OpenType 'loader' for Plain TeX and LaTeX
installed:   Yes
revision:    52738
cat-date:    2019-11-11 10:37:48 +0100
```

**Comment by u-fischer** [comment]
Copy & paste from your pdf works fine for me. I get (in the adobe reader on windows) 

beneficial beneficial

I also uncompressed your pdf and the ToUnicode mappings looks for the two glyph and the two font fine:

~~~~
<0307> <00660069>
<0416> <00660069>
~~~~
 
So I would assume that your pdf viewer is faulty.

**Comment by krono** [comment]
Thanks for checking!

Indeed, Adobe Reader, on OS X 10.12 in my case, works for copy&paste.

I initially tried Mac Preview (or any Quartz application for that matter, like Skim) and there, copy&paste does not work.

I also verified, using XeTeX exhibits the same behavior.

Shall I close?

**Comment by krono** [comment]
Ok, I'm closing this. Sorry for the noise.

This is obviously some MacOS-specific nonsense.

For the record: Even creating a PDF via TextEdit with an OTF-based font will have ligatures non-copyable, at least with Preview on OS X 10.12.
