### ISSUE TITLE
using ~/.texlive2020 instead of ~/.texlive2019

### ISSUE THREAD

**Issue by kberry** [latex3/luaotfload#129]
I just noticed that luaotfload-tool is currently writing its cache to
~/.texlive2020/texmf-cache/luatex-cache/generic/fonts/otl

... but TL20 won't be released for a while yet. Seems like it would be cleaner to use the release year instead of the calendar year?

**Comment by u-fischer** [comment]
Hm. It doesn't happen for me. Are you sure that you don't have some texmf.cnf around that could confuse luaotfload-tool here?

**Comment by kberry** [comment]
I see nothing in my setup referring to ~/.texlive2020. I am using the
distributed texmf.cnf and texmfcnf.lua, and the string "2020" does not
appear in either one.

Is there anything in the debugging output that can tell me where it came
from? All I see is:

luaotfload | db : Font names database loaded from /home/karl/.texlive2020/texmf-cache/luatex-cache/generic/names/luaotfload-names.luc

Thanks,
Karl

**Comment by u-fischer** [comment]
well imho it should use texmfvar, so the question is why it is different for you.

**Comment by kberry** [comment]
$ kpsewhich -var-value TEXMFVAR
/home/karl/.texlive2019/texmf-var

If I remove ~/.texlive*/texmf-cache, it just gets recreated in that same
place.

It does use the expected $TEXMFVAR on another machine (same versions of
everything).

I have not customized anything that I know of. So, once again ... is
there something in the debugging output that can help track it down?
I don't see it. Thanks.

**Comment by u-fischer** [comment]
You can run `luaotfload-tool --diagnose=environment`, perhaps it shows at least the variable that is the problem.

**Comment by zauguin** [comment]
@kberry Which value does `kpsewhich` return for `TEXMFCACHE`?

**Comment by kberry** [comment]
thanks much. TEXMFCACHE was indeed the culprit. sorry for my mistake.
