### ISSUE TITLE
Contact GitHub support to “unfork” this repository

### ISSUE THREAD

**Issue by khaledhosny** [latex3/luaotfload#132]
Some GitHub features are not available for forks (like code search, which I needed today). I think it would be nice to contact GitHub support to unkmark this project as a fork (this is handled upon request since there is no exposed controls for repository maintainers to do so) since this is the actual luaotfload repository now and no longer a fork (in GitHub sense).

**Comment by josephwright** [comment]
I've got GitHub to sort this
