### ISSUE TITLE
Luaotfload cannot detect third-party fonts installed system-wide on Windows 10

### ISSUE THREAD

**Issue by manuelboni** [latex3/luaotfload#137]
After a *full* install of TeXLive 2019, I have noticed that `luaotfload` can:
- load first-party fonts that come bundled with Windows (for example 'Segoe UI')
- load third-party fonts installed on my texmf-local directory (for example 'Vollkorn', downloaded from its homepage)

but unfortunately it cannot detect third-party fonts installed on Windows' 'Fonts' directory.
After discussing this problem on the lualatex-dev mailing list,
@u-fischer suggested that I should make sure that the font is actually available system-wide.
So after that I tried to install the 'Inter' font by dragging and dropping the font files into the `C:\Windows\Fonts` directory, and then I tried to load the font with `fontspec`, both through its name ('Inter Regular'), and its file name (`Inter-Regular.ttf`). Unfortunately `luaotfload` cannot find it either way.

OS: Windows 10 Pro 1909 64-bit
TeX distribution: TeXLive 2019 with the latest updates.

Thank you for your attention.

**Comment by zauguin** [comment]
I just tried installing that font on Windows (10 Pro, 1909) and it worked without problems, so it seems to be a system-specific issue.

I was not able to drag and drop anything to C:\Windows\Fonts though, dragging a file there was completely ignored and I had to install the font through a right click on the font file and selecting something like "install system-wide". So are you sure that you actually installed the font? Especially, is the font listed if you open C:\Windows\Fonts?

If yes, then please send us a copy of your font name database `luaotfload-names.lua.gz`. You can probably find it under `%USERPROFILE%\.texlive2019\texmf-var\luatex-cache\generic\names` or in your TeXLive directory under `...\2019\texmf-var\luatex-cache\generic\names`.

**Comment by manuelboni** [comment]
Installing the fonts as suggested by @zauguin solved the problem, though I am baffled by the fact that installing fonts on something that looks like a system directory would just install them for a single user... Windows idiosyncrasies I guess... Closing, and thanks for you help.
