### ISSUE TITLE
Detect fonts installed for a single user on Windows

### ISSUE THREAD

**Issue by zauguin** [latex3/luaotfload#138]
Every now and then, someone seems to try using fonts with luaotfload which are installed only for a single user on Windows. We should probably support this. 

Does anyone know where such fonts are stored and why they are not included in our normal search paths?

**Comment by u-fischer** [comment]
I just made a try. Installing a font as user put the fonts in 

          %userprofile%\AppData\Local\Microsoft\Windows\Fonts

The local installation path is rather new but I don't really remember when the option appeared.

**Comment by u-fischer** [comment]
After changing in luaotfload-database the get_os_dirs like this:

~~~~
    elseif os.type == "windows" or os.type == "msdos" then
        local windir = osgetenv("WINDIR")
        local appdata = osgetenv("LOCALAPPDATA")
        return { filejoin(windir, 'Fonts'), filejoin(appdata, 'Microsoft/Windows/Fonts')  }
    else
~~~~

the fonts in the user folders are found for me.

**Comment by zauguin** [comment]
@u-fischer Thanks, I pushed the change as 9fa3dec92d9aced2ffc5122fd450146affa14499
