### ISSUE TITLE
[dev] Ligatures=TeX in harf mode

### ISSUE THREAD

**Issue by dohyunkim** [latex3/luaotfload#139]
```latex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Noto Sans CJK KR}
  [ Renderer=HarfBuzz, Ligatures=TeX, Script=Hangul, Language=Korean ]
\begin{document}
`A'
``A''
\end{document}
```
<img width="334" alt="스크린샷 2020-03-17 오후 3 29 12" src="https://user-images.githubusercontent.com/4328134/76828730-eff43a00-6864-11ea-83f6-599828bab84c.png">

Running with `lualatex-dev`, apostrophe is not replaced as shown, while this issue does not occur with `lualatex`.
Note that in the above example HarfBuzz tacitly applied opentype GSUB feature to the apostrophe.

**Comment by zauguin** [comment]
Thank you. Fixed in `dev`.
