### ISSUE TITLE
luaotfload.main() produces "attempt to call a nil value" error

### ISSUE THREAD

**Issue by h-kitagawa** [latex3/luaotfload#145]
When `luaotfload.main()` is called explicitly, it produces an error, instead of `Luaotfload initialization requested but is already loaded, ignoring.` message.

```
% plain LuaTeX
\input luaotfload.sty
\directlua{luaotfload.main()}
\bye
```
This gives
```
(./multiple_lotf_main.tex
(/opt/texlive/2020/texmf-dist/tex/luatex/luaotfload/luaotfload.sty
(/opt/texlive/2020/texmf-dist/tex/latex/base/ltluatex.tex))...020/texmf-dist/te
x/luatex/luaotfload/luaotfload-main.lua:284: attempt to call a nil value (globa
l 'logreport')
stack traceback:
        ...020/texmf-dist/tex/luatex/luaotfload/luaotfload-main.lua:284: in field 'mai
n'
        [\directlua]:1: in main chunk.
l.2 \directlua{luaotfload.main()}

?
```

Note that `\RequirePackage[2020-02-01]{latexrelease}` produces the same error as above.

LuaTeX: 1.12.0 (TeX Live 2020), luaotfload: 3.12 (2020-02-02).

**Comment by zauguin** [comment]
This should be fixed in `dev` as of 03fb787893d4f5b66eeffdcace931753b8480d49. Can you please test this?

**Comment by h-kitagawa** [comment]
03fb787 seems to work fine. Thanks.

**Comment by u-fischer** [comment]
@zauguin latex explicitly sets luaotfload.main to `_void` after the loading. Is this still needed after your change?

**Comment by zauguin** [comment]
@u-fischer It is a bit weird: Actually ltluatex does it the other way around: It sets a unused local `_void` to the (non-existent) return value of `luaotfload.main()`. That doesn't have any effect, especially since `_void` directly runs out of scope, so it is independent from this but it can be removed.
