### ISSUE TITLE
luaotfload-tool --list=basename fails in version 3.13

### ISSUE THREAD

**Issue by u-fischer** [latex3/luaotfload#149]
C:\texlive\2020\bin\win32\runscript.tlu:935: ...e/2020/texmf-dist/scripts/luaotfload/luaotfload-tool.lua:1297: bad argument #1 to 'match' (string expected, got nil)

`luaotfload-tool --list=basename:*` 

works.

**Comment by u-fischer** [comment]
fixed in https://github.com/latex3/luaotfload/commit/32b5616dba670bf1288958ecd53513aa8720d5e3

**Comment by u-fischer** [comment]
fixed in version 3.14 just uploaded

**Comment by ticelso** [comment]
Mr. uf-fischer.
C:\texlive\2020\bin\win32\runscript.tlu:935: C:\texlive\2020\bin\win32\runscript.tlu:730: attempt to index a nil value ) 
I have a blema very similar to yours and I am not able to solve it.
