### ISSUE TITLE
Error runscript.tlu:935 and runscript.tlu:730

### ISSUE THREAD

**Issue by ticelso** [latex3/luaotfload#153]
C:\texlive\2020\bin\win32\runscript.tlu:935: C:\texlive\2020\bin\win32\runscript.tlu:730: attempt to index a nil value )
I have problem very similar to yours and I am not able to solve it.
This only happens when I'm going to use PHP to run the command line:
`$arr1=[]; $int1=""; exec("latexmk -xelatex GM9HFG5JDYVXL.tex", $arr1, $int1);`

**Comment by zauguin** [comment]
This is not an issue related in any way to `luaotfload`.
