### ISSUE TITLE
Font Skolske: not continuously binding letters at various places

### ISSUE THREAD

**Issue by olsak** [latex3/luaotfload#154]
The free variant of font Skolske is available at https://www.skolskepismo.sk/stiahnut-pismo/. Sorry, you must fill an email and accept GDPR processing with email and then the button "Stiahnut" allows you to load the zip file wit the font and with example PDF. Now, you can prepare following testing file:

    \input luafonts
    \font\f="[Skolske Free Light]" at 25pt
    
    \f Slovenska
    \end

The luatex test.tex generates PDF where the letters n..s are not continuously bind. All other letter pairs are working. The non-working letter pairs depends on the whole words and they occur at Cca 10 % cases.
When I try the same testing file (without \input luafonts which runs luaotfoad, of course) with XeTeX, then all letter-pairs are correctly bind.
luaotfload: ver 3.14, luatex ver 1.12.0

**Comment by zauguin** [comment]
It's a problem related to hyphenation: The fontloader breaks the glyphs around possible hyphenation points. One workaround is using `harf` mode:

```
\input luaotfload.sty
\font\f="[Skolske Free Light]:mode=node,script=latn" at 25pt

\f Slovenska
\end
```
This does restrict the hyphenation points though, the font is pretty strongly affected by #152. Especially with `harf` mode every word will only allow hyphenation at at most one point.

**Comment by olsak** [comment]
Your example does not work, it is much worse. None character pairs are bounded, the result looks like S l o v e n s k a.
One workaround is

    \input luaotfload.sty
    \font\f="[Skolske Free Light]" at 25pt
    \hyphenchar\f=-1

    \f Slovenska
    \end

But I mean that there is a bug in the luaotfload.

**Comment by u-fischer** [comment]
I tried @zauguin's code and the result looks like this:

![image](https://user-images.githubusercontent.com/4047173/83277412-4d482800-a1d2-11ea-8329-d7467a15f8e5.png)

If you didn't get this: Are you sure that you used lua**hb**tex for the compilation and not luatex? harf mode needs the harfbuzz library.

**Comment by zauguin** [comment]
> Your example does not work, it is much worse. None character pairs are bounded, the result looks like S l o v e n s k a.

Please read the whole comment:

> This of course requires `luahbtex`.

mode=hard only works if you compile with luahbtex instead of luatex.

**Comment by olsak** [comment]
It means that luatex is not supported by luaotfload developers? I prefer luatex. I said this in my first message in this thread: luatex  ver 1.12.0. No hb.
I belive that with luahbtex it works. But my report is concerned to luatex.

**Comment by u-fischer** [comment]
the fontloader code for node mode as is used by luatex is developed by the context team. luaotfload only imports it. If you want improvement here you should write to the context list.

**Comment by olsak** [comment]
I don't understand. When luatex (no hb) loads some lua codes from ../tex//luatex/luaotfload (no hb) then all these codes are only a copy 1:1 from another project?

**Comment by zauguin** [comment]
@olsak 
> I don't understand. When luatex (no hb) loads some lua codes from ../tex//luatex/luaotfload (no hb) then all these codes are only a copy 1:1 from another project?

`luaotfload` is (at least without HarfBuzz) mostly the glue to integrate the ConTeXt fontloader with LaTeX (and also other formats). Some parts are independent from the ConTeXt code (e.g. the system for finding and matching fonts, some additional font features, ...) and some parts, especially the basic font shaper (The code which actually lays out the glyphs and selects the right glyphs in the font) is not modified. 

So no, not all these codes are a 1:1 copy, but the specific section which causes this issue comes from ConTeXt.

**Comment by olsak** [comment]
I tried \input luatex-fonts (which is from ConTeXt) intead \input luaotfload.sty and the result differ. First one does not bind any pair of characters but second one does not bind only pairs at the hyphenation boundaries. This means that the issue differs. I cannot to test Skolske font directly in ConText because I don't know how to do this.

**Comment by u-fischer** [comment]
with a current context and 

~~~~
\starttext 
\font\f={name:Skolske Free Light:mode=node;script=latn;} at 25pt

\f Slovenska
\stoptext
~~~~

I get 

![image](https://user-images.githubusercontent.com/4047173/83303774-f48e8480-a1fd-11ea-8613-2be745d19cb6.png)

As the output depends on hyphenation it is quite possible that the result differ from LaTeX or plain text.

**Comment by zauguin** [comment]
ConTeXt enables a different set of features by default. To get the same effect, you have to enable the `liga` feature:

```
\starttext 
\font\f={name:Skolske Free Light:mode=node;script=latn;+liga;} at 25pt

\f Slovenska
\stoptext
```
![image](https://user-images.githubusercontent.com/962229/83311402-64f1d180-a20f-11ea-8ddb-9e2555a4431e.png)

**Comment by car222222** [comment]
Marcel’s output using liga shows that this still does not work at the word-break point, between ‘n’ and ‘s’.
With luatex, would adding \hyphenation {slovenska} fix that?  
But this is not, of course, a general solution.

**Comment by olsak** [comment]
As I wrote above, \hyphenchar\f=-1 solves this problem, but we cannot use hyphenation patterns when printing with this font. Maybe this font needs not hyphenation, because it is intended to create templates for pupils (first grade of elementary school). But, in principle, there is something wrong in OTF font loader.

**Comment by u-fischer** [comment]
As already said: we are not maintaining this part of the code. Report the issue to the context maintainer. I'm closing the issue for now. You can reopen it if there has been an upstream change that we should import.
