### ISSUE TITLE
Concurrent LuaTeX runs writing to the same font cache

### ISSUE THREAD

**Issue by krumeich** [latex3/luaotfload#157]
Hello there! I'm not altogether sure whether this is the right place for my question. If not, kindly point me towards a more suitable forum to address.

I'm using TeX Live in a Docker container to compile several documents concurrently in a CI setup. Every document has its own directory. I use latexmk and LuaLaTeX. With TeX Live 2019 (and previous) this worked perfectly: There was no interference between the concurrent compiles. With TeX Live 2020 however, the setup is broken. Some documents fail to build, because latexmk complains about exceeding its maximum number of runs.

I've narrowed it down to a problem with dependencies in latexmk. Please take a look at these two log snippets. The first one is the _old_ setup, where everything used to work fine:

    Rule 'pdflatex': File changes, etc:
      Changed files, or newly in use since previous run(s):
      'ate_main.aux'
      'ate_main.lof'
      'ate_main.lot'
      'ate_main.run.xml'
      'ate_main.toc'

The second snippet, with TeX Live 2020, shows an additional changed file:

    Rule 'pdflatex': File changes, etc:
      Changed files, or newly in use since previous run(s):
      '/usr/local/texlive/texmf-var/luatex-cache/generic-dev/names/luaotfload-lookup-cache.luc'
      'ate_main.aux'
      'ate_main.lof'
      'ate_main.lot'
      'ate_main.run.xml'
      'ate_main.toc'

It seems that all 8 concurrent instances of latexmk write to the `luaotfload-lookup-cache.luc` file. To me it looks like a race condition. 

Anyway, this problem could either be attributed to latexmk (it should ignore the cache file) or to luaotfload (it should not continuously write to the file). I thought I might start here and see if any you people have a good idea or a workaround.

You can find the document repository in question at https://github.com/n-design/n-doc_template
The docker image is at https://github.com/n-design/n-doc

Thank you for your attention.

Alexander

**Comment by u-fischer** [comment]
it is a bit confusing that you names your rule "pdflatex" ;-). 

The cache file changes for me if I change the font setup in a document. I don't quite see how to avoid this, after all this is the main purpose of the cache. So imho (if this is the cause of your problem) luatexmk should ignore the change here. Alternativly you could set a dedicated texmfvar  for each of your runs, then they will no longer share the file.

**Comment by krumeich** [comment]
Ulrike! Thanks for replying so quickly. I added a dedicated TEXMFCACHE variable to each run. That solved the problem. Uses a bit more storage, but what the heck. 

As a side note: Your hint finally made me look into my .latexmkrc a bit further. Fixed the rule names now. Thanks for that, too.

**Comment by krumeich** [comment]
If someone runs into the same problem, there's a workaround: Have latexmk ignore the .luc files when scanning for updates. See the thread at https://tug.org/pipermail/tex-live/2022-March/047948.html for details.
