### ISSUE TITLE
lualatex math tables not working

### ISSUE THREAD

**Issue by LiquidDragonFire** [latex3/luaotfload#160]
I just updated MikTeX and found that a .tex file which previously created the right output under lualatex no longer does so. However, xelatex does create the correct output.

The problem seems to be that lualatex is not picking up the opentype MATH tables for stretchy symbols in the Unicode private use area. It works correctly with the standard stretchy symbols such as \left{ and \right}. Note that the \OpnBracS and \ClsBracS have the \left and \right baked in. Those symbols are found in the logix.otf file and the symbols are defined in logix.sty, both of which are in the logix package. Here is some test code.

```
    \documentclass[10pt]{article}
    \usepackage{logix}
    \newcommand \testFrac   {\frac{1}{2+\frac{3}{4}}}
    \newcommand \testFrak   {\frac{\frac{\frac{\frac{1}{1}}{\frac{1}{1}}}{\frac{\frac{1}{1}}{\frac{1}{1}}}}{\frac{\frac{\frac{1}{1}}{\frac{1}{1}}}{\frac{\frac{1}{1}}{\frac{1}{1}}}}}
    
    \begin{document}
       $ \OpnBracS \testFrac \ClsBracS $ \hspace{2em} $ \OpnBracS \testFrak \ClsBracS $
       \end{document}

```
This is the output from xelatex

![image](https://user-images.githubusercontent.com/67171689/85182593-22904300-b257-11ea-8a59-381609c947a4.png)

And here is the output from lualatex

![image](https://user-images.githubusercontent.com/67171689/85182628-3dfb4e00-b257-11ea-9cdf-c926e07e2031.png)

**Comment by zauguin** [comment]
@LiquidDragonFire Are you the maintainer of the `logix` package?

**Comment by zauguin** [comment]
The font is a bit odd, it gets loaded with script set to latin (aka `latn`) instead of `math`, so it's affected by the fix for https://github.com/latex3/luaotfload/issues/148: The automatic system identifies it as a text font and therefore disables math handling by default.

From our end it basically works as designed, so two possible fixes would be:

  1. Change the font to contain the math script and load with `script` set to `math`. (If no features are needed you don't really have to change the font and can just change the script directly, but then fontspec can't be used because it tries to be smart and messes with the settings)
  2. If that should not be possible, add the `-nomathparam` font feature to explicitly overwrite the automatic detection.

**Comment by LiquidDragonFire** [comment]
Marcel,

Thanks for your response. Yes, I am the maintainer of the logix package.

It is correct that logix.otf has Latin specified. The lower 128 characters are
the Latin Unicode range. The other Unicode range is the Private Use Area which
contains all of the remaining symbols (several thousand). There is a fairly
large MATH table, but all of it is for symbols in the PUA. The font is correct
in this respect.

If I change the font to indicate that it contains one of the mathematical code
ranges, that will be incorrect since it does not, and that in turn could
potentially cause problems when loading the font (such as by a browser). If
the MATH table is not empty it should be loaded. If it is not empty then it
should be presumed that there symbols somewhere that use that table.
Otherwise, that font would be incorrect because the contents of the MATH table
could not possibly be valid.

Just because a font is a text font does not mean that it does not contain any
mathematical symbols requiring the use of the MATH table.

The logix.sty package loads the font as follows

   \newfontface \logix {logix.otf}[Scale=1.0,NFSSFamily=logix]

   \DeclareSymbolFont{Logix}{TU}{logix}{m}{n}

is this where -nomathparamfont should be used?

Note that this does work with XeLaTex and it worked correctly with LuaLaTex
until the fix you mentioned was applied. It seems that the fix may have
corrected problems with one font and broke another the logix font. Perhaps the
fix would be to ignore a minimal MATH table?

It is not entirely clear to me what you are doing that broke things. From what
I see the fix is a patch for a specific font. If that font is correct, perhaps
the fix should have been to a different area?

All of that is above my pay grade. I would just like my package to work
without potentially breaking the font elsewhere.

Please let me know what I should do.

Thank you.

Michael Lee Finney

**Comment by LiquidDragonFire** [comment]
Marcel,

I changed the PREFIX section of features to contain

   languagesystem DFLT dflt;
   languagesystem latn dflt;
   languagesystem math dflt;

instead of

   languagesystem DFLT dflt;
   languagesystem latn dflt;

which is consistent with the STIX2 math .otf font. That also contains

   languagesystem latn ROM ; # Latin Romanian
   languagesystem cyrl dflt; # Cyrillic default
   languagesystem grek dflt; # Greek default

which is not appropriate for the logix font since it does not contain any of
those symbols. That did not change the output.

If by "load with script set to math" you mean to use \setmathfont, then that
won't work because the logix font supplements, but does not replace, the
primary math font.

Michael Lee Finney

**Comment by zauguin** [comment]
> If I change the font to indicate that it contains one of the mathematical code ranges, that will be incorrect since it does not, and that in turn could potentially cause problems when loading the font (such as by a browser).

The script `math` used in the feature tables GPOS and GSUB do not "indicate that [the font] contains one of the mathematical code ranges", that script tag is generally to be used for math layout features ([as specified in the specification of the `math` table](https://docs.microsoft.com/en-us/typography/opentype/spec/math#opentype-layout-tags-used-with-the-math-table). So a font which does not contain normal mathematical symbols but is supposed to be used with math layout systems would still be expected to use it.

> I changed the PREFIX section of features to contain
> ```
> languagesystem DFLT dflt;
> languagesystem latn dflt;
> languagesystem math dflt;
> ```
>
> instead of
>
> ```
> languagesystem DFLT dflt;
> languagesystem latn dflt;
> ```
> which is consistent with the STIX2 math .otf font.

You might have to additionally assign at least one feature to this script in order for it to be actually used, but then you should be able to load it as math font.

> If by "load with script set to math" you mean to use \setmathfont, then that won't work because the logix font supplements, but does not replace, the primary math font.

You don't have to use `\setmathfont`, you can also specify the relevant parameters yourself. Try

```
\newfontface \logix {logix.otf}[Renderer=Basic,Script=Math,Scale=1.0,NFSSFamily=logix]
```



> The logix.sty package loads the font as follows
> ```
> \newfontface \logix {logix.otf}[Scale=1.0,NFSSFamily=logix]
> \DeclareSymbolFont{Logix}{TU}{logix}{m}{n}
> ```
> is this where -nomathparamfont should be used?

Yes, if you use that approach you need

> ```
> \newfontface \logix {logix.otf}[Scale=1.0,NFSSFamily=logix, RawFeature=-nomathparam]
> ```

**Comment by LiquidDragonFire** [comment]
Marcel,

Thank you.

I found that [Renderer=Basic,Script=Math,Scale=1.0,NFSSFamily=logix] worked
with and without Renderer=Basic. However, XeLaTex did not like Script=Math.
What is the purpose of Renderer=Basic?

I also found that [Scale=1.0,NFSSFamily=logix, RawFeature=-nomathparam] worked
for bot LuaLaTex and XeLaTex. Is this because XeLaTex does not have that
fixup? Is this approach the minimal possible approach with the least possible
impact?

Since I can load the font differently based on LuaLaTex or XeLaTex, which
approach do you recommend? Are there any internal differences that would be
significant?

Michael Lee Finney

**Comment by u-fischer** [comment]
What do you mean by "XeLaTex did not like Script=Math"? 

But anyway: Imho the clean solution with lualatex is the solution with `Script=Math`. xelatex knows neither the Renderer=Basis nor the nomathparam switch, so you can leave it out there.

**Comment by LiquidDragonFire** [comment]
The console output said:

Package fontspec Warning: Font "logix" does not contain requested Script
(fontspec)                "Math".

LauLaTex does not do that.

I also find that for LuaLaTex, if I use Renderer=Harfbuzz or Renderer=OpenType
that the math tables are ignored regardless of what else that I use.

**Comment by u-fischer** [comment]
> The console output said: Package fontspec Warning: Font "logix" does not contain requested Script (fontspec) "Math".

Are you sure that xelatex finds the right font? Its search pathes are different and if you have more than one version it could pick up an older one. Use `\XeTeXtracingfonts=1` to check. 



> I also find that for LuaLaTex, if I use Renderer=Harfbuzz or Renderer=OpenType that the math tables are ignored regardless of what else that I use.

Math should use  Renderer=Basic.

**Comment by LiquidDragonFire** [comment]
Yes. XeLaTex finds the correct font. Every exported symbol and script is
present and appears to be correct. The only difference is the warning on the
console. If it picked up an older font (not that there should be one), then my
documentation file would fail to compile because it would not contain the last
two symbols added.

**Comment by LiquidDragonFire** [comment]
The problem appears to be resolved using Math=Script.

**Comment by LiquidDragonFire** [comment]
The problem is resolved. The answers were very helpful. They were actually in the updated documentation for luaotfload -- but I did not know to look there since I do not actually directly use that package.
