### ISSUE TITLE
letterspace is applied twice after unhbox

### ISSUE THREAD

**Issue by u-fischer** [latex3/luaotfload#167]
extracted from https://tex.stackexchange.com/questions/561821/fontspecs-letterspace-disturbing-tabbing-luatex-only

~~~~
\documentclass{book}

\usepackage{fontspec}
\setmainfont{texgyreheros}

\begin{document}

\fboxsep=0pt
\setbox0\hbox{CAPS}
\rule{\wd0}{1pt}

\fbox{\unhbox0}

\setbox0\hbox{\addfontfeature{LetterSpace=30}CAPS}

\rule{\wd0}{1pt}

\fbox{\copy0}

\fbox{\unhbox0}

\setbox0\hbox{\hbox{\addfontfeature{LetterSpace=30}CAPS}}

\rule{\wd0}{1pt}

\fbox{\copy0}

\fbox{\unhbox0}
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/92513796-2954a380-f211-11ea-9a39-5bd407c20dbb.png)

**Comment by zauguin** [comment]
This should be fixed, but it still needs some testing especially when letterspacing occurs both inside and outside of the unhbox.
