### ISSUE TITLE
Error running luaotfload-tool --find

### ISSUE THREAD

**Issue by jpintar** [latex3/luaotfload#168]
`luaotfload-tool --find="Latin Modern Roman"` (or any other font, with or without `-F`) fails with version 3.15 (up-to-date TeX Live 2020 on Windows 10), returning `C:\texlive\2020\bin\win32\runscript.tlu:935: ...texmf-dist/tex/luatex/luaotfload/luaotfload-features.lua:432: attempt to index a nil value (field 'normal')`.

A self-test with `--diagnose=files` reports `mktests`, `mkstatus`, `mkcharacters`, `mkglyphlist`, and `mkimport` as missing. All other self-tests are fine.

**Comment by zauguin** [comment]
Thank you for the report. This is fixed in the `dev` branch by 6d746704 and therefore will be fixed with the next release.
