### ISSUE TITLE
luaotfload-tool is broken (73: attempt to compare string with number)

### ISSUE THREAD

**Issue by nicolashainaux** [latex3/luaotfload#170]
Hello,

I installed TeX Live via `tlmgr` on a Linux Mint box. I downloaded the install script just a few moments ago.
When trying to run luaotfload-tool, it outputs:

```
$ luaotfload-tool --version
/usr/local/texlive/2020/bin/x86_64-linux/luaotfload-tool:73: attempt to compare string with number
```
(same result without the `--version` flag)

**Comment by zauguin** [comment]
Thanks for reporting the issue. Do you have TeXLive 2019 installed on your system?
What does `which texlua` output?

**Comment by nicolashainaux** [comment]
No, TeX Live 2019 is not installed. It's fresh Linux Mint install actually.

```
$ which texlua
/usr/bin/texlua
```

I've tried to fix the issue by wrapping all the `status.luatex_version` occurences in line 73 in `tonumber ()` calls, and this works, but then I get another problem:
```
$ luaotfload-tool --version
/usr/local/texlive/2020/bin/x86_64-linux/luaotfload-tool:108: module 'lualibs' not found:
	no field package.preload['lualibs']
	[kpse lua searcher] file not found: 'lualibs'
	[kpse C searcher] file not found: 'lualibs'
```
so I wonder if there's not something wrong in my install.

Here's what I did to install, if that may be relevant: I chose the minimal scheme when I ran the install script. Once installed, I added the following packages:
`tlmgr install xcolor lxfonts amsmath eurosym stackengine scalerel fontspec polyglossia siunitx pgf hyperref cancel placeins ulem tools graphics epstopdf textpos parskip geometry latex-bin epstopdf-pkg infwarerr grfext kvoptions pstricks pst-eps moreverb pst-tools collection-luatex`. This is exactly what I need to compile my documents on FreeBSD.

I've tried to add `lualibs`, but:
```
$ sudo /usr/local/texlive/2020/bin/x86_64-linux/tlmgr install lualibs
tlmgr: package repository https://mirrors.chevalier.io/CTAN/systems/texlive/tlnet (verified)
tlmgr install: package already present: lualibs
```

So, as to the "compare string with number" problem, I guess there is something to fix in the script, but I wonder why this has not been noticed before. (Maybe there's something else that's missing on my box?)

**Comment by zauguin** [comment]
> So, as to the "compare string with number" problem, I guess there is something to fix in the script, but I wonder why this has not been noticed before. (Maybe there's something else that's missing on my box that makes it fail?)

Yes, that one is fixed in the dev branch (there was a tonumber missing) but it was never observed because it only triggers if you have LuaTeX version 1.10 and the current version of the check was only introduced in TeXLive 2020 which ships with LuaTeX 1.12.

That's why I asked about TeXLive 2019: Your `texlua` executable has LuaTeX 1.10 which was shipped in TeXLive 2019. That's consistent with the path: Your TeXLive files seem to be under /usr/local, but texlua is under /usr/bin.

So for some reason, you seem to have a system installed older version of texlua which is found before your regular texlua. Maybe your PATH contains /usr/bin before your TeXLive path?

**Comment by nicolashainaux** [comment]
Yes, that's the problem!! Thank you very much!!
I've put the TeX Live directories at start of the `PATH` in my `.bashrc` instead of the end, and this solves the case:
```
$ luaotfload-tool --version
112
luaotfload-tool:
        Luaotfload font management and diagnostic utility.
        License: GNU GPL v2.0.
        Report problems to <https://github.com/latex3/luaotfload/issues>

luaotfload-tool version: "3.15"
Revision: nil
Lua interpreter: stock; version "Lua 5.3"
Luatex version: 1.12
Platform: type=unix name=linux
    +  machine: x86_64
    + nodename: xantico
    +  release: 5.4.0-48-generic
    +  sysname: Linux
    +  version: #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
No database metadata available.
```
(Though I don't know why `texlua` got installed in `/usr/bin`, maybe another package at some point installed it as a dependency?)

Thank you very much!
