### ISSUE TITLE
undesired print-ln on terminal and log

### ISSUE THREAD

**Issue by olsak** [latex3/luaotfload#172]
Please, read my comment to @zauguin 's commit [here](https://github.com/latex3/luaotfload/commit/ff56872dba73d7ae5a6827c4c98468ad64efb84f).
I see that it is corrected but only in dev branch. Please, give mi an estimation when this bug will be removed in a new CTAN release of luaotfload.
I must do an [absurd hack](https://github.com/olsak/OpTeX/commit/db33c98422254f46f4286e30605513b71ecad759) in my macros now.

**Comment by u-fischer** [comment]
there will be an update probably before the end of the year. 

And while I agree that the empty lines don't look good, I don't see the necessity for some hacks to avoid them. The terminal output doesn't need to win a design price.

**Comment by olsak** [comment]
Thank you for time estimation. Your last sentence is opinion-based. My hack will be here until the luaotfload will be fixed. It is my macros, I decide what to do. The fact is that luaotfload have a bug now.
