### ISSUE TITLE
Devanagari (letter ra) error

### ISSUE THREAD

**Issue by jbezos** [latex3/luaotfload#180]
It seems the letter ra (र) is still problematic. The following M(non)WE raises an error:
```
\documentclass{article}

\usepackage{fontspec}

\setmainfont{Shobhika}[Renderer=Harfbuzz, Script=Devanagari]
  
\patterns{1र}

\begin{document}

ग्लेशियर नेशनल पार्क अमेरिकी राष्ट्रीय उद्यान

\end{document}
```
The error is:
```
warning  (node filter): error: ...exmf-dist/tex/luatex/luaotfload/luaotfload-ha
rf-plug.lua:455: attempt to perform arithmetic on a nil value (field 'nextclust
er')
```
**But**, if the line with the pattern is commented out it works.

**Comment by u-fischer** [comment]
works ok for me with the development branch.

**Comment by zauguin** [comment]
I can't reproduce this either.

**Comment by jbezos** [comment]
I trust you 🙂. I will be waiting for the updates.

**Comment by NiranjanTambe** [comment]
I am getting a similar error for my documents, but I am not sure how to install the dev version. I followed the instructions from the README and cloned the git repository, issued `l3build install` from the main folder; I think the process was successful (not 100% sure though!) as there was no error-message on my terminal. In fact nothing prompted after I issued the command, it just finished its task without any noise. Now `kpsewhich luaotfload.sty` returns `/home/niru/texmf/tex/luatex/luaotfload/luaotfload.sty`.

Even after doing all of this, lualatex-dev (v1.13.2) with `luaotfload-dev` (2021/01/08 v3.17) produces this error.

**Comment by zauguin** [comment]
@NiranjanTambe I'll take a closer look later, but

  1. Make sure that you ran `git checkout dev` before running  `l3build install`.
   2. Compile your document with `lualatex-dev`, not `lualatex`.

**Comment by NiranjanTambe** [comment]
Yes, I didn't mention it, but I have taken care of both of your points.

**Comment by NiranjanTambe** [comment]
> Make sure that you ran git checkout dev before running l3build install.

Sorry, just to be sure; `git checkout dev` or `git checkout dev-2.9`?

**Comment by NiranjanTambe** [comment]
I am sorry, that was my bad! I was installing `dev-2.9` branch. `l3build install` on `dev` branch produced the the correct output :)
