### ISSUE TITLE
Bizarre date format in "luaotfload-tool --dumpconf"

### ISSUE THREAD

**Issue by Ndolam** [latex3/luaotfload#181]
The output of this command (on a RPi4 running raspbian) contains:

;; on 2021-04-d 12:35:27. Configuration variables

I've never seen anyone output the day of the month in hex before.  Is this a new style?

**Comment by blefloch** [comment]
On 4/14/21 5:48 PM, Ndolam wrote:
> The output of this command (on a RPi4 running raspbian) contains:
> 
> ;; on 2021-04-d 12:35:27. Configuration variables
> 
> I've never seen anyone output the day of the month in hex before. Is this a new
> style?

The key question is whether this "d" is 13 in hex or simply stands for day and
wasn't converted properly by whatever process puts there the date.

**Comment by u-fischer** [comment]
@blefloch  it is a simple typo in the code, the % is missing:


~~~~
osdate ("%Y-%m-d %H:%M:%S", os.time ())))
~~~~

**Comment by Ndolam** [comment]
I was wondering what was in the code (I guess I coulda looked).  But it is interesting that I discovered this on the 0xd-th day of the month.

**Comment by Ndolam** [comment]
P.S.  I was just joking about the possibility that someone would write the date in hex.  In case that wasn't clear.

**Comment by zauguin** [comment]
Fixed in 25c8416264477abbec96d0b88ee426a0e0dcce6c.
