### ISSUE TITLE
Loading svg-font via inkscape fails

### ISSUE THREAD

**Issue by hselig-github** [latex3/luaotfload#183]
Hi!
Not sure, but from scanning the inkscape pages it seems that they have changed the shell mode syntax. From the lua-code in fontloader-2021-01-07.lua I take it that so far commands where passed in the format `temp-otf-svg-shape-1.svg --export-file=temp-otf-svg-shape-1.pdf`. However, the new way seems to be (cf. https://wiki.inkscape.org/wiki/index.php/Using_the_Command_Line, tbc, I'm not an expert on this) `file-open:temp-otf-svg-shape-1.svg; export-filename:temp-otf-svg-shape-1.pdf; export-do`.

Consequently, the luaotfload code would have to be adjusted. I am not sure what the purpose of the function inkscapeformat("pdf") is if itreturns the extension instead of "filename", so please verify below.

I made the following change to get fontload to work for me:

```
diff -C 2 fontloader-2021-01-07.lua fontloader-2021-01-07.lua.orig
*** fontloader-2021-01-07.lua	2021-04-23 18:11:38.305607694 +0200
--- fontloader-2021-01-07.lua.orig	2021-01-16 23:25:10.000000000 +0100
***************
*** 28211,28215 ****
     local f_svgfile=formatters["temp-otf-svg-shape-%i.svg"]
     local f_pdffile=formatters["temp-otf-svg-shape-%i.pdf"]
!    local f_convert=formatters["file-open:%s; export-%s:%s; export-do\n"]
     local filterglyph=otfsvg.filterglyph
     local nofdone=0
--- 28211,28215 ----
     local f_svgfile=formatters["temp-otf-svg-shape-%i.svg"]
     local f_pdffile=formatters["temp-otf-svg-shape-%i.pdf"]
!    local f_convert=formatters["%s --export-%s=%s\n"]
     local filterglyph=otfsvg.filterglyph
     local nofdone=0
```

Here a minimal lualatex file to check/confirm:
```
\documentclass{minimal}
\usepackage{fontspec}
\newfontfamily\fooFont[RawFeature={+svg;}]{ColorTube.otf}
\begin{document}
\fooFont
Color Font
\end{document}
```

Translate with `lualatex --shell-escape foo.tex`. The font I used can be found here: (https://www.behance.net/gallery/39274241/Colortube).

Version I used:
TeXLive 2021, luaotfload ist Version 3.17.
Inkscape 1.0.1 (3bc2e813f5, 2020-09-07)
    Pango version: 1.46.2

Original errors in foo.log:
```
This is LuaHBTeX, Version 1.13.2 (TeX Live 2021) 
 system commands enabled.
(./foo.tex
LaTeX2e <2020-10-01> patch level 4
 L3 programming layer <2021-02-18>
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/minimal.cls
Document Class: minimal 2001/05/25 Standard LaTeX minimal class
) (/usr/local/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3backend/l3backend-
luatex.def))
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3packages/xparse/xparse-
2020-10-
01.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3packages/xparse/xparse-
generic.
tex)))
(/usr/local/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec-luatex.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/fontenc.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(./b.aux
) (/usr/local/texlive/2021/texmf-dist/tex/latex/base/ts1cmr.fd)    Pango
version: 1.46.2
verbs_action: Invalid verb: temp-otf-svg-shape-4.svg --export-
filename=temp-otf-svg-shape-4.pdf

...

verbs_action: Invalid verb: temp-otf-svg-shape-88.svg --export-
filename=temp-otf-svg-shape-88.pdf
 [1{/usr/local/texlive/2021/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] (./foo.aux))
 366 words of node memory still in use:
   3 hlist, 1 vlist, 1 rule, 2 glue, 3 kern, 1 glyph, 4 attribute, 40 glue_spec, 4 attribute_list, 1 write nodes
   avail lists: 1:1,2:15,3:2,4:1,5:17,6:2,7:40,9:14
<./ColorTube.otf>
Output written on foo.pdf (1 page, 6020 bytes).
Transcript written on foo.log.
```

Hope this helps to make this functionality work going forward. And thanks to all of you who created this package!!

Cheers,
Hendrik

**Comment by Keks-Dose** [comment]
> Hi!
> Not sure, but from scanning the inkscape pages it seems that they have changed the shell mode syntax. From the lua-code in fontloader-2021-01-07.lua I take it that so far commands where passed in the format `temp-otf-svg-shape-1.svg --export-file=temp-otf-svg-shape-1.pdf`. However, the new way seems to be (cf. https://wiki.inkscape.org/wiki/index.php/Using_the_Command_Line, tbc, I'm not an expert on this) `file-open:temp-otf-svg-shape-1.svg; export-filename:temp-otf-svg-shape-1.pdf; export-do`.
> 
> Consequently, the luaotfload code would have to be adjusted. I am not sure what the purpose of the function inkscapeformat("pdf") is if itreturns the extension instead of "filename", so please verify below.
> 
> I made the following change to get fontload to work for me:
> 
> ```
> diff -C 2 fontloader-2021-01-07.lua fontloader-2021-01-07.lua.orig
> *** fontloader-2021-01-07.lua	2021-04-23 18:11:38.305607694 +0200
> --- fontloader-2021-01-07.lua.orig	2021-01-16 23:25:10.000000000 +0100
> ***************
> *** 28211,28215 ****
>      local f_svgfile=formatters["temp-otf-svg-shape-%i.svg"]
>      local f_pdffile=formatters["temp-otf-svg-shape-%i.pdf"]
> !    local f_convert=formatters["file-open:%s; export-%s:%s; export-do\n"]
>      local filterglyph=otfsvg.filterglyph
>      local nofdone=0
> --- 28211,28215 ----
>      local f_svgfile=formatters["temp-otf-svg-shape-%i.svg"]
>      local f_pdffile=formatters["temp-otf-svg-shape-%i.pdf"]
> !    local f_convert=formatters["%s --export-%s=%s\n"]
>      local filterglyph=otfsvg.filterglyph
>      local nofdone=0
> ```
> 
> Here a minimal lualatex file to check/confirm:
> 
> ```
> \documentclass{minimal}
> \usepackage{fontspec}
> \newfontfamily\fooFont[RawFeature={+svg;}]{ColorTube.otf}
> \begin{document}
> \fooFont
> Color Font
> \end{document}
> ```
> 
> Translate with `lualatex --shell-escape foo.tex`. The font I used can be found here: (https://www.behance.net/gallery/39274241/Colortube).
> 
> Version I used:
> TeXLive 2021, luaotfload ist Version 3.17.
> Inkscape 1.0.1 (3bc2e813f5, 2020-09-07)
> Pango version: 1.46.2
> 
> Original errors in foo.log:
> 
> ```
> This is LuaHBTeX, Version 1.13.2 (TeX Live 2021) 
>  system commands enabled.
> (./foo.tex
> LaTeX2e <2020-10-01> patch level 4
>  L3 programming layer <2021-02-18>
> (/usr/local/texlive/2021/texmf-dist/tex/latex/base/minimal.cls
> Document Class: minimal 2001/05/25 Standard LaTeX minimal class
> ) (/usr/local/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec.sty
> (/usr/local/texlive/2021/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
> (/usr/local/texlive/2021/texmf-dist/tex/latex/l3kernel/expl3.sty
> (/usr/local/texlive/2021/texmf-dist/tex/latex/l3backend/l3backend-
> luatex.def))
> (/usr/local/texlive/2021/texmf-dist/tex/latex/l3packages/xparse/xparse-
> 2020-10-
> 01.sty
> (/usr/local/texlive/2021/texmf-dist/tex/latex/l3packages/xparse/xparse-
> generic.
> tex)))
> (/usr/local/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec-luatex.sty
> (/usr/local/texlive/2021/texmf-dist/tex/latex/base/fontenc.sty)
> (/usr/local/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
> (./b.aux
> ) (/usr/local/texlive/2021/texmf-dist/tex/latex/base/ts1cmr.fd)    Pango
> version: 1.46.2
> verbs_action: Invalid verb: temp-otf-svg-shape-4.svg --export-
> filename=temp-otf-svg-shape-4.pdf
> 
> ...
> 
> verbs_action: Invalid verb: temp-otf-svg-shape-88.svg --export-
> filename=temp-otf-svg-shape-88.pdf
>  [1{/usr/local/texlive/2021/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] (./foo.aux))
>  366 words of node memory still in use:
>    3 hlist, 1 vlist, 1 rule, 2 glue, 3 kern, 1 glyph, 4 attribute, 40 glue_spec, 4 attribute_list, 1 write nodes
>    avail lists: 1:1,2:15,3:2,4:1,5:17,6:2,7:40,9:14
> <./ColorTube.otf>
> Output written on foo.pdf (1 page, 6020 bytes).
> Transcript written on foo.log.
> ```
> 
> Hope this helps to make this functionality work going forward. And thanks to all of you who created this package!!
> 
> Cheers,
> Hendrik

@hselig-github 

I tested your change, because I like the font. However, in your example I don't get öäü, while ÖÄÜ work. 

In the resulting PDF, instead of öäü => oau. Same happens if I replace the letter with \symbol{"00FC} for ü, e.g. Many other glpyhs, while existing, won't be printed in the PDF, "," "*" "-" and so on. 

texlive 21 on linux.

**Comment by hselig-github** [comment]
@Keks-Dose Guess your problem is a different one, and not related to luaotfload. If I preview the ColorTube font in my font manager, my "ÄÖÜäöüß" test string renders as "ÄÖÜaous". That's under Linux. So my assumption is either the glyphs aren't there in the first place, or their diacritics are located too far off (which I assume is the case, as the font manager's character preview cuts off all diacritics and the top of tall letters). I would suggest that you address it to the creator of the ColorTube font (https://www.behance.net/gallery/39274241/Colortube).

The issue in this thread is specific about the code in luaotfload's fontloader routines.

Cheers,
Hendrik

**Comment by zauguin** [comment]
Sorry for not answering sooner. The issue has been [forwarded to the ConTeXt team](https://mailman.ntg.nl/pipermail/ntg-context/2021/102092.html) which develops the fontloader component and has been fixed there. The current `dev` version has an almost working version (it fails only for the first SVG font in a document) but the next ConTeXt upload will solve that issue too.
