### ISSUE TITLE
Some glyphs do not show up in compiled PDF with variable OTF of Noto Sans CJK SC

### ISSUE THREAD

**Issue by xry111** [latex3/luaotfload#184]
```tex
% luatex
\input luaotfload.sty

\font\a=[NotoSansCJKsc-VF.otf]:axis={wght=500}

\a

U+6D4B 测

U+8BD5 试

U+5E2E 帮

U+90FD 都

\bye
```

In the compiled PDF file, U+6D4B and U+8BD5 show up correctly, but U+5E2E and U+90FD don't show up.  However, `pdftotext` still prints them.

NotoSansCJKsc-VF.otf is downloaded at https://github.com/googlefonts/noto-cjk/raw/main/Sans/Variable/OTF/NotoSansCJKsc-VF.otf.

Only a few glyphs don't show up: I tried a full article (with at least 100 Chinese glyphs), and only U+5E2E and U+90FD didn't show.  I can't find any "special qualities" of these two glyphs.

Another strange thing is: with https://github.com/googlefonts/noto-cjk/raw/main/Sans/Variable/OTF/NotoSansMonoCJKsc-VF.otf (just the monospace version of Noto Sans CJK SC) instead of NotoSansCJKsc-VF.otf, the glyphs show up correctly.

Tested with TexLive 2021.

**Comment by zauguin** [comment]
This has been [fixed upstream by the ConTeXt team](https://mailman.ntg.nl/pipermail/ntg-context/2021/102092.html) and is merged into the current development branch. There is a smaller remianing issue about cache versions, but that will be fixed with the next ConTeXt upload.
