### ISSUE TITLE
Putting side-to-side things shaped with different shapers causes spaces to be lost or to have a reversed effect

### ISSUE THREAD

**Issue by callegar** [latex3/luaotfload#186]
In response to a suggestion provided in bug #185, I am now trying to use the harf shaper for parts of the text using a font that employs PUA-A and PUA-B to avoid their codepoints to be changed.

Unfortunately, mixing the harf and the node renderer seems to have nasty effects.

Consider this bit of code

```latex
\documentclass{article}
\usepackage{fontspec}
\newfontface\MDI{Material Design Icons}[Renderer=HarfBuzz]

\begin{document}
Look at this character {\MDI \char"F1372}~test.
\end{document}
```

the compiled PDF appears to be broken because the symbol U+F1372 ends up overlapping onto the "t" of test rather than being spaced from it because of the `~`. In fact, the `~` appears to have the opposite effect than it should, causing the overlap, where without it you would have the two things just placed side to side. The more `~`s you add, e.g. as in `~~~~~~~~test` the more you end up shifting the "test" word to the left to the point that you can make it overlap with "character" as well.  Using a regular space `\ ` rather than `~` has the very same outcome.

**Comment by zauguin** [comment]
This should be fixed in `dev`.

**Comment by callegar** [comment]
As a workaround, until this is released, boxing the material works (though it is really only applicable when you have just a word to be typeset with the different shaper).
