### ISSUE TITLE
harf-plug.lua error if \showoutput is used with bibmap fonts 

### ISSUE THREAD

**Issue by u-fischer** [latex3/luaotfload#189]
The following example uses a bitmap font and  errors if `\showoutput` is used with 

~~~~
....\T1/wesu/m/n/10  (ligature |...nstall/tex/latex-dev/luaotfload/luaotfload-
harf-plug.lua:1138: bad argument #1 to 'utfchar' (value out of range).
<argument> ...not:N \tex_shipout:D \box_use:N \l_shipout_box 
                                                  \__shipout_drop_firstpage_...
l.29 \end{document}
~~~~

~~~~
\documentclass{article}
\usepackage{wesu}
\begin{document}\showoutput
\wesu
international
\end{document}
~~~~

**Comment by zauguin** [comment]
Fixed in `dev` (b02c538a1431bdc3863bff5a00832579b1822ede). It actually wasn't about bitmaps but classical TeX ligatures with left or right boundary characters...

**Comment by u-fischer** [comment]
Works now. Actually I got the error as I wanted to look why luatex looses an n and a here (tons of ligatures involved ...):

```
\documentclass{article}
\usepackage{wela}
\begin{document}
\showoutput
\wela%
international
\end{document}

```

![image](https://user-images.githubusercontent.com/4047173/121547319-53d7c500-ca0c-11eb-9ba5-0f533ddeaf4e.png)

**Comment by zauguin** [comment]
Fixed in the latest release.
