### ISSUE TITLE
LuaTeX cannot justify monospace fonts with the Node Renderer

### ISSUE THREAD

**Issue by callegar** [latex3/luaotfload#190]
On an up to date TeXLive (LuaHBTeX, Version 1.13.2 (TeX Live 2021)), the following snippet causes line breaking issues

```LaTeX
\documentclass[12pt, twoside]{article}
\usepackage{fontspec}
\setmainfont{Source Code Pro}
\usepackage{blindtext}

\begin{document}
\blindtext
\clearpage
\blindtext
\end{document}
```
Switching to the OpenType renderer solves the issue. Unclear to me if the issue is with luaotfload or the engine.

**Comment by zauguin** [comment]
The behavior of the node shaper is intentional: Since the font is monospace, spaces get constant width too. Having monospaced glyphs with variable width spaces would be pointless. Similarly, expansion would go against the fundantal idea of monospaced fonts.

Without either expansion, stretchable spaces (or even hyphenation which gets disabled by default for properly declared monospace fonts) justification isn't possible.

IMO the HarfBuzz shaper should be adjusted to match the fontloader behavior.
@u-fischer What do you think?

**Comment by u-fischer** [comment]
The behaviour of both shaper should be the same imho. And I think the default to have a constant width for the word space is ok too, as they are mostly used in listings. But there are people who use a typewriter font as text font and an imho option to switch on variable spaces  would allow them to use them with justification without having to declare the fontdimens manually.

**Comment by callegar** [comment]
@zauguin I was expecting something like that. There is a nasty incompatibility with the xeTeX engine, though, even if I understand that this is the original TeX and pdfTeX behavior.

To some extent, it is also something that I have never really fully understood. LaTeX has 4 main ways of aligning text:
- left aligned (ragged right)
- right aligned (ragged left)
- justified
- centered

*Both* the last two really make no sense with a monospaced font if you want to preserve the character alignment (unless you want to do as very old word processors used to do: approximating the centering to the "character" and doing justification by filling in extra spaces — which leads to an uneven interword spacing).

However, there is already an inconsistency: LaTeX will happily break the character alignment for centering. As an additional inconsistency, the default `\parindent` will break the alignment, the default list indents will break the alignment, etc. It is really not enough to switch off the variable width spaces to guarantee the alignment of the characters to a rigid grid.

Furthermore, there is an asymmetry: if you want to preserve the alignment with a monospace font on an engine that justifies by using variable width spaces even in the monospace case (like xeTeX or current luaTeX with the Harf renderer), then it is enough to move to a ragged right alignment, that incidentally seems to be always a sane thing to do unless you are a fan of overfull lines. However, if you are on an engine that avoids variable width spaces with monospaced fonts like pdfLaTeX/luaLaTeX, how do you get the justification by variable spaces?

Finally, from a purely practical point of view, I find very little usefulness in this intended behavior, as you get it out of the box. If I am not missing something, there are 3 main reasons for using a monospaced font:
1. because you are typesetting something for which the fixed spacing is needed (code often);
2. because you need the aesthetics of a typewriter font;
3. because for some norm in certain legal documents you must use a typewriter font.

In none of them, the current behavior is optimal. In 1. it will give you very poor line breaks with most of the lines protruding into the right margin or even out of the page unless you couple it with a \raggedright or a \sloppy. In 2 and 3 you want the justification by variable width spaces (yes, also in 3, where the ratio of the norm is to guarantee an upper bound on the number of alphabetic characters on the line).

As a conclusion, I'd like to advocate:
- the introduction of a 'switch' in the font selection commands enabling the usage of monospace fonts as if they were regular fonts;
- some coordination with the xeTeX developers, to get a consistent behavior on both engines.

**Comment by davidcarlisle** [comment]
> However, if you are on an engine that avoids variable width spaces with monospaced fonts like pdfLaTeX...

This isn't (mostly) an engine level thing. Certainly in the case of pdftex it isn't, the standard latex monospace fonts specify a fixed space in their metrics, pdftex just does what the font specifies, it could use variable space, or the macro package could impose variable space even if the font does not specify it. Of course for opentype fonts there is some variability in how the tex-style stretchy interword space is interpreted from the tables in the font and that leads to differences in the modes as you note.

So this version of the test document gives no warnings without needing to change modes or change luaotfload or the engine.
In practice any macro layer commands setting up monospace fonts need to set the space either fixed or variable so any engine setting is at best a rough default.


```
\documentclass[12pt, twoside]{article}
\usepackage{fontspec}
\setmainfont{Source Code Pro}
\spaceskip=.5em plus .5em
\xspaceskip=.5em plus .5em
\usepackage{blindtext}

\begin{document}
\blindtext
\clearpage
\blindtext
\end{document}
```

**Comment by callegar** [comment]
@davidcarlise What would be the way to force the metrics using `\fontdimen` in place of `\spaceskip` and `\xspacesckip` like in your example?

I see that
```
\fontdimen3\font=0.5\fontdimen2\font
\fontdimen4\font=0.33\fontdimen2\font
```
seems to do the job, but it is unclear to me what I should put instead of `\font` to actually change the fontimens for the font I like rather than the current font.  How do the font names get assigned when I set up a family with fontspec?

**Comment by zauguin** [comment]
In v3.18-7-g6665ac9c this has been made consistent for both shapers and configurable:

  * Non-monospace fonts have stretchable and shrinkable spaces by default, they get fixed spaces by adding `+fixedspace`.
  * Monospace fonts have non-stretchable spaces by default, they an be made stretchable by adding `-fixedspace`.
  * As usual, these are only defaults and the macro layer is free to do whatever it wants.

**Comment by zauguin** [comment]
> What would be the way to force the metrics using `\fontdimen` in place of `\spaceskip` and `\xspacesckip` like in your example?

Messing with the fontdimens is a bad idea. For one, they have to be changed for every individual internal font (so e.g. separately for every fontsize you might use, every member of the family, every use of `\addfontfeature` or similar, etc.), the name of the font depends on the NFSS family names which is not reliably predictable when fontspec is used, and it interferes with caching and might therefore affect unintended places. It's best to leave the fontdimens for the font defaults and use the macro level controls (especially `\spaceskip` and `xspaceskip`) when control from the macrolevel is required.
