### ISSUE TITLE
error: attempt to call a nil value (upvalue 'setfield')

### ISSUE THREAD

**Issue by olsak** [latex3/luaotfload#194]
Suppose this example
```
\input luaotfload.sty
\font\f=[BaskervilleF-BoldItalic]:script=latn;+tlig; at10pt

\f ABCabc

\bye
```
and process it by `luatex test`. The result is
```
warning  (node filter): error: ...xmf-dist/tex/luatex/luaotfload/fontloader-202
1-05-20.lua:446: attempt to call a nil value (upvalue 'setfield')
```
The previous version of `fontloader-2021-01-07` was without this problem. This error appeared in version `fontloader-2021-05-20`.

The error isn't in the font loading process but when the `\par` is processed after the text ABCabc. And if we change the text to ABC abc (with space) or to ABabc then the error disappear. This error is bounded only to the font BaskervilleF-BoldItalic. I don't know any other font which can give this error.
I guess that this would be a problem of fontloader from ConTeXt, not of luaotfload additional lua code. But I am a "customer" of the luaotfload package as a whole, so I am reporting the problem here.

**Comment by vlasakm** [comment]
@olsak Can you try this change?

```
--- a/a/fontloader-2021-05-20.lua
+++ b/b/fontloader-2021-05-20.lua
@@ -276,7 +276,7 @@ nuts.setcomponents=direct.setcomponents
 nuts.setdirection=direct.setdirection
 nuts.setdisc=direct.setdisc
 nuts.setreplace=direct.setreplace
-nuts.setfield=setfield
+nuts.setfield=direct.setfield
 nuts.setkern=direct.setkern
 nuts.setlink=direct.setlink
 nuts.setlist=direct.setlist
```

**Comment by vlasakm** [comment]
I invistigated a bit further on the background of this. I sent the details to the ConTeXt mailing list.

https://www.mail-archive.com/ntg-context@ntg.nl/msg99099.html

**Comment by olsak** [comment]
I confirm that the patch to the fontloader mentioned above solves this issue. The question remains who applies it and when.

**Comment by zauguin** [comment]
> I confirm that the patch to the fontloader mentioned above solves this issue. The question remains who applies it and when.

I send this to Hans this morning together with a related change to be applied on the ConTeXt side. As general policy, we don't patch the imported ConTeXt code.(We could fix this without patching, but that would be hack and be pointless since hans will probably apply it before the next luaotfload release anyway.

**Comment by zauguin** [comment]
Fixed in the latest release.
