### ISSUE TITLE
Error with lualatex in TeX Live 2021 when using LetterSpace feature in combination with \emph and - (see https://tex.stackexchange.com/q/604753/14147)

### ISSUE THREAD

**Issue by sieversMartin** [latex3/luaotfload#195]
The following example compiles on a TeX Live 2020 system (`This is LuaHBTeX, Version 1.12.0 (TeX Live 2020)`), but fails on a most recent TeX Live 2021 (`This is LuaHBTeX, Version 1.13.2 (TeX Live 2021)  (format=lualatex 2021.7.3)`).

`! error:  (nodes): trying to delete an attribute reference of a non attribute node`

What is so special about the combination of `LetterSpace` feature, `\emph` macro and `-` in the example? Is this a bug in LuaLaTeX? `fontspec` versions are the same.

``` latex
% !TeX TS-program = lualatex

\listfiles
\documentclass{article}
\usepackage{fontspec}
\newfontfamily{\trackingfont}{lmroman10}
[%
Extension   = .otf,%
UprightFont = *-regular,%
ItalicFont  = *-italic,%
LetterSpace = 12.5,%
]%

\begin{document}
AAA \emph{BBB}-CCC% works

{\trackingfont AAA BBB-CCC}% works

{\trackingfont AAA \emph{BBB} CCC}% works

{\trackingfont AAA \emph{BBB}-CCC}% does not work

\end{document}
```

Package list on TeX Live 2020:
```
*File List*
 article.cls    2020/04/10 v1.4m Standard LaTeX document class
  size10.clo    2020/04/10 v1.4m Standard LaTeX file (size option)
fontspec.sty    2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
  xparse.sty    2021-01-09 L3 Experimental document command parser
   expl3.sty    2021-02-18 L3 programming layer (loader) 
l3backend-luatex.def    2021-03-18 L3 backend support: PDF output (LuaTeX)
xparse-2020-10-01.sty    
fontspec-luatex.sty    2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX

 fontenc.sty
fontspec.cfg
  ts1cmr.fd    2019/12/16 v2.5j Standard LaTeX font definitions
 ***********
```

**Comment by zauguin** [comment]
This is fixed in `dev`. @sieversMartin If you need a temporary workaround until the next version is released, you can remove the line

              attribute_table[attr_list] = getattributelist(start)

in your copy of `luaotfload-letterspace.lua`. (Should be around line 448)

**Comment by sieversMartin** [comment]
Thank you.
