### ISSUE TITLE
Using bundled fonts causes regeneration of luc files

### ISSUE THREAD

**Issue by ilyapopov** [latex3/luaotfload#196]
So, my idea was to bundle fonts with the documents, such that my collaborators do not need to install the fonts. For that, I created `fonts` subdir within the document directories. Then I told `fontspec` to look in that directory. However, I noticed that when I compile another document, the luc files get regenerated (they have different hash, but the same size). This takes time (especially if the document uses many font variants) and causes unnecessary recompiles.

This is the minimal reproducer tex file:

```latex
\documentclass[a4paper]{article}

\usepackage{fontspec}
\setmainfont{Libertinus Serif}[
  Path = fonts/ ,
  Extension = .otf ,
  UprightFont = *-Regular
]

\begin{document}
Example text
\end{document}
```

Attached is the reproducer case. There are two directories, `document1` and `document2`. Contents of these directories is identical. Each has a tex file shown above and a fonts directory with a copy of `LibertinusSerif-Regular.otf`. The script `run.sh` runs the reproducing steps.
If i compile the first document with 
    
    lualatex document.tex

and then check the md5sum of the luc file `$HOME/.texlive2020/texmf-var/luatex-cache/generic/fonts/otl/libertinusserif-regular.luc`, I get `c26d6194f61514a2d81a6a3dc26c3084`. Then I run the same command in the second directory, and I get `4911b827ba6eba965f49f1b6236b8bac`.

[repro.zip](https://github.com/latex3/luaotfload/files/6889166/repro.zip)

Possible reason is that path to the font file is encoded into the luc file. If the path changes, the luc is regenerated. This makes sense. However, the luc file is global. Doing something strictly within the directory of my document should not affect other documents. It would be nice if it was possible to put luc files into a location local to the document, or may be encode font file location (path) or its hash sum into *filename* of the luc file, so luc files of different documents don't keep overwriting each other.

**Comment by ilyapopov** [comment]
Possibly related to #166 or #40.

**Comment by ilyapopov** [comment]
I did a little more diffing. Corresponding lua file changes too. The only difference is a time stamp:

```
$ diff after-document1.lua after-document2.lua 
27783c27783
<  ["time"]=1627423293,
---
>  ["time"]=1627423345,
```

**Comment by zauguin** [comment]
> It would be nice if it was possible to put luc files into a location local to the document, or may be encode font file location (path) or its hash sum into _filename_ of the luc file, so luc files of different documents don't keep overwriting each other.

As discussed in the issue you linked, this is already done for fonts which use the HarfBuzz based shaper and will not be done for the default node shaper since it would require patching of the fontloader.



> I did a little more diffing. Corresponding lua file changes too. The only difference is a time stamp:
> 
> ```diff
> $ diff after-document1.lua after-document2.lua 
> 27783c27783
> <  ["time"]=1627423293,
> ---
> >  ["time"]=1627423345,
> ```

The files don't match based on the path since the path might differ even if the files are identical (Think symlinks/hardlinks/different mount locations/moved files/etc.), but one of the factors which is considered is the modification date. That's the time difference you see: The fontfile found for document2 was created about a minute later than the one found for document1, proving that they are not the same file.

**Comment by ilyapopov** [comment]
Or, indeed this is mentioned in that issue. Sorry, I missed that.

So it sees that modification time of the font file is different and that triggers regeneration of the cache files. That makes sense.

So what would be the advice to avoid constant regeneration of the cache? I am going to try using harf shaper and see what happens.

**Comment by zauguin** [comment]
> So what would be the advice to avoid constant regeneration of the cache? I am going to try using harf shaper and see what happens.

Beside using the harf shaper you could rename the font file. (A more hacky approach would be to copy the fonts in a way which preserves attributes such that the modification time is the same.)
