### ISSUE TITLE
PDF/A validation bug for a variety of fonts

### ISSUE THREAD

**Issue by lenoleno** [latex3/luaotfload#206]
PDF/A validation (with [verapdf](https://verapdf.org/software/)) of documents created with LuaLaTeX fails with a font related error (for a variety of fonts).  I have no idea what software component actually introduces the error (the font, luaotfload, luatex engine, even verapdf).  So, please bear with me.

# System

* OS: XUbuntu 20.04
* TeX Live 2019 managed via `apt`
* luatex: This is LuaTeX, Version 1.10.0 (TeX Live 2019/Debian)
* package `fonts-ubuntu` v0.83-4ubuntu1
* veraPDF v1.18.6, Greenfield parser

# Symptoms

PDF/A validation works with some fonts, but changing font may invalidate the otherwise unchanged LaTeX document.  An example error message reported by _veraPDF_ using font _Ubuntu_ is (copied from the GUI program's HTML output):

```
Validation information
Rule	Status
Specification: ISO 19005-2:2011, Clause: 6.2.11.4, Test number: 4	
If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program, regardless of whether a CID in the font is referenced or used by the PDF or not.	Failed
1 occurrences 	
PDCIDFont	
fontFile_size == 0 || fontName.search(/[A-Z]{6}\+/) != 0 || CIDSet_size == 0 || cidSetListsAllGlyphs == true	
root/document[0]/pages[0](5 0 obj PDPage)/contentStream[0](7 0 obj PDContentStream)/operators[11]/font[0](BUDZNO+Ubuntu)/DescendantFonts[0](BUDZNO+Ubuntu)
```

# Steps to reproduce

1. Compile the attached LaTeX file with `lualatex`:

        $ lualatex bug-pdfa.tex

1. Check PDF/A validity with veraPDF on CLI:

        $ path/to/verapdf --format text bug-pdfa.pdf

    The `--format text` option enables terse output.  To see the actual error message, run `verapdf` with option `--format xml` or see the XML or HTML output of the veraPDF GUI program (`verapdf-gui`).

1. In the TeX file, uncomment any of the given fonts commands to test a different font.

# Expected behaviour

PDF/A validation works for any font (as far as the bug is not in the font).  Otherwise, LuaLaTeX can not reliably be used for the generation of PDF/A documents.  Which were unfortunate, given the ever-growing importance of PDF standards for shared documents.

# User question

Is this bug actually related to package `luaoftload`?

**Comment by lenoleno** [comment]
As `.tex` files cannot be attached, here's the LaTeX code:

```LaTeX
\begin{filecontents*}{\jobname.xmpdata}
\Title{PDF/A font issue}
\end{filecontents*}
\documentclass{article}
\usepackage[a-2b]{pdfx}
\usepackage{fontspec}
% Working:
%\setmainfont{Latin Modern Roman}
%\setmainfont{TeX Gyre Pagella}
%\setmainfont{TeX Gyre Cursor}
%\setmainfont{Ubuntu Mono}
%\setmainfont{DejaVu Sans Mono}
% Failing:
\setmainfont{Ubuntu}
%\setmainfont{IBM Plex Sans}
%\setmainfont{Fantasque Sans Mono}
%\setmainfont{DejaVu Sans}
\pagestyle{empty}
\begin{document}
1
\end{document}
```

**Comment by u-fischer** [comment]
Try with `\pdfvariable omitcidset=1`   See https://tex.stackexchange.com/a/474336/2388

**Comment by lenoleno** [comment]
Attaching sample PDF output using Ubuntu font.
[bug-pdfa.pdf](https://github.com/latex3/luaotfload/files/7627839/bug-pdfa.pdf)

**Comment by lenoleno** [comment]
Investigating ...

**Comment by lenoleno** [comment]
@u-fischer: Thanks!  Will bring this to the attention of _pdfx_ package maintainers, again.  That oversight should really be fixed before TL2022.

This bug can now be closed.
