### ISSUE TITLE
Deformed character rendering with variable TTF fonts

### ISSUE THREAD

**Issue by adunning** [latex3/luaotfload#209]
When using a TTF variable font, some characters are rendered in a deformed manner. This does not occur with OTF variable fonts.

This can be seen with [Source Serif](https://github.com/adobe-fonts/source-serif):

```tex
\documentclass{article}

\usepackage{fontspec}
\usepackage{blindtext}

\defaultfontfeatures{RawFeature={+axis={wght=100}}}
\setmainfont{Source Serif 4 Variable}

\begin{document}

\blindtext

\end{document}
```

Result with `SourceSerif4Variable-Roman.ttf`:

<img width="1643" alt="Screenshot 2022-01-05 at 23 31 58" src="https://user-images.githubusercontent.com/1084407/148304601-708a579c-db41-423d-93be-c3a9749f5137.png">

With `SourceSerif4Variable-Roman.otf` (expected):

<img width="1671" alt="Screenshot 2022-01-05 at 23 32 46" src="https://user-images.githubusercontent.com/1084407/148304662-a5f8ebed-a4e5-49ca-a381-f8e2426f22df.png">

I am also able to reproduce this with the [Junicode beta](https://github.com/psb1558/Junicode-font).

**Comment by psb1558** [comment]
I'll just add that I'm very interested in seeing this issue addressed, as I believe that variable fonts have a lot to offer to LuaTeX users, and that the technologically advanced TeX community will be a receptive audience for this font technology, if the software supports it adequately. I've managed to make the new version of my Junicode font [work with LuaTeX](https://github.com/psb1558/Junicode-font/discussions/92) by generating a cff2 version, but most variable fonts are ttf-flavored, and they do not (yet) work reliably with luaotfload.

**Comment by zauguin** [comment]
This is already fixed in the development sources and therefore will be fixed in the next version.

**Comment by zauguin** [comment]
Fixed in the latest release.
