### ISSUE TITLE
directory change for the database

### ISSUE THREAD

**Issue by hvoss49** [latex3/luaotfload#214]
Before latest update a 

`luaotfload-tool --update --force`

saved the database files into   `.../texmf-var/luatex-cache/generic/names`

but now it is saved in   `.../texmf-var/luatex-cache/generic-dev/names`

but I do not use the dev versions of the programs.

Is it the intended behaviour??

**Comment by zauguin** [comment]
Thanks for the report. It's not intentional and is being fixed in v3.20 together with another bug in luaotfload-tool.
