### ISSUE TITLE
Harfbuzz prevents TeX ligatures if ligaturing callback is used

### ISSUE THREAD

**Issue by wehro** [latex3/luaotfload#220]
The output of the following document contains the correct `fi` and `ff` ligatures. However, ``` `` ```, `--`, and `''` are not turned into “, –, and ”.
```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Latin Modern Roman}[Renderer=HarfBuzz]
\directlua{luatexbase.add_to_callback("ligaturing", function(head,tail) end, "do nothing")}
\begin{document}
``fi--ff''
\end{document}
```

**Comment by zauguin** [comment]
That seems pretty much like the point of the `ligaturing` callback. IMO this is expected behavior.

**Comment by wehro** [comment]
I reported because the behaviour is different with the Node renderer. Is this also expected?

**Comment by zauguin** [comment]
Yes. The `ligaturing`/`kerning` callbacks control the built-in behavior of LuaTeX which is utilized in different ways by the renderers so changing them (especially in weird ways like disabling them) has quite different effects on them. You will see even bigger effects for the `base` renderer (there it should disable ligatures completely).
