### ISSUE TITLE
\input luaotfload.sty does not work (for some fonts)

### ISSUE THREAD

**Issue by hrpunio** [latex3/luaotfload#229]
\input luaotfload.sty
\def\MainSFont{Chaparral Pro} %% does not work (for smcp/onum)
%\def\MainSFont{name:TeXGyrePagella} %% works
% ** smcp/onum ignored **
\font\sc = "\MainSFont:+tlig;+smcp;+lnum} at 9.9pt
%% Old style numbers
\font\sco = "\MainSFont:+tlig;+smcp;+onum" at 9.9pt

\def\SwUA{Stand with Ukraine}
\def\dig{0123--456---789}

{\sc \SwUA \dig } vs {\sco \SwUA \dig }
\bye
%%% if LuaLaTeXed with fontspec, ie:
%% \setmainfont[Letters=SmallCaps,Numbers=OldStyle]{ChaparralPro}
%% both works
%% (if \input luaotfload.sty ermoved and XeTeXed also works)

seems fontspec is more clever or plain stuff outdated?

**Comment by zauguin** [comment]
I don't have the font, but features are generally script and language specific and you specify neither. Fontspec will default to Latin, while luaotfload will use the default script of nothing is specified.

**Comment by u-fischer** [comment]
You can check in the log how exactly fontspec specifies the font and copy that in your plaintex document.

**Comment by hrpunio** [comment]
thanks u-fischer, I even inspected log, but obviously failed to find relevant info:-)
(The font is a free one https://www.wfonts.com/font/chaparral-pro)

**Comment by FrankMittelbach** [comment]
> (The font is a free one https://www.wfonts.com/font/chaparral-pro)

btw, doesn't look like a free font to me, even if so advertised on some sites

**Comment by FrankMittelbach** [comment]
@hrpunio this is a general problem, a lot of the font sites seem to claim stuff as being free and if you look a little deeper it is not true (not sure what their business model is, try to get ad clicks?). This font, for example, is Adobe and can be licensed from their site, I have not looked into the font, sometime you see more with otfinfo.

**Comment by hrpunio** [comment]
was not aware (really) but actually this site looks hmmm .... suspicious
https://www.wfonts.com/contact

**Comment by FrankMittelbach** [comment]
so it is, it is a bit like those books on which people can upload free books (and you as the author can complain if your book is there and for some surprising reason is not for free --- except that there is no way to complain or get through to the site owners). Same with many of these "free fonts" sites. If you want a good font, pay the designer he or she gets little enough for their work, or use one of the really free sites where the "designer" has given the font away.
