### ISSUE TITLE
babel, marathi and harfbuzz error

### ISSUE THREAD

**Issue by niruvt** [latex3/luaotfload#230]
With the following code:

```
\documentclass{article}
\usepackage{babel}
\babelprovide[import,main]{marathi}
\usepackage{fontspec}
\setmainfont[%
  Script=Devanagari,%
  Renderer=Harfbuzz%
]{Shobhika}% https://ctan.org/pkg/shobhika

\begin{document}
र्यनि
\end{document}
```

I get [this](https://pastebin.com/LCXs3djJ) log. What is causing these errors? I am using fully updated TL.

**Comment by u-fischer** [comment]
your fontloader is too old, you have `fontloader-2021-01-07.lua`. A current system should have `fontloader-2022-06-15.lua`.  So probably you have some older luaotfload somewhere.

**Comment by niruvt** [comment]
Thanks, I deleted that folder and now it is working correctly. Closing the issue.
