### ISSUE TITLE
How to specify an instance name with a space for a variable font

### ISSUE THREAD

**Issue by bgvoisin** [latex3/luaotfload#231]
As the subject says, is there a syntax for specifying an instance name with a space? I couldn't find the answer in the luaotfload doc, tried using the instance name directly, putting it between `{}` or `""`, replacing the space by `_` (or even `\␣`,or `\space`), nothing seems to work.

I was experimenting using the variable font functionality with the venerable Skia.ttf from macOS, for which the predefined instances are (as revealed by ttx from fonttools)

```
    <!-- Black -->
    <NamedInstance flags="0x0" subfamilyNameID="289">
      <coord axis="wght" value="3.2"/>
      <coord axis="wdth" value="1.0"/>
    </NamedInstance>

    <!-- Extended -->
    <NamedInstance flags="0x0" subfamilyNameID="293">
      <coord axis="wght" value="1.0"/>
      <coord axis="wdth" value="1.3"/>
    </NamedInstance>

    <!-- Condensed -->
    <NamedInstance flags="0x0" subfamilyNameID="295">
      <coord axis="wght" value="1.0"/>
      <coord axis="wdth" value="0.61998"/>
    </NamedInstance>

    <!-- Light -->
    <NamedInstance flags="0x0" subfamilyNameID="296">
      <coord axis="wght" value="0.48"/>
      <coord axis="wdth" value="1.0"/>
    </NamedInstance>

    <!-- Regular -->
    <NamedInstance flags="0x0" subfamilyNameID="297">
      <coord axis="wght" value="1.0"/>
      <coord axis="wdth" value="1.0"/>
    </NamedInstance>

    <!-- Black Extended -->
    <NamedInstance flags="0x0" subfamilyNameID="298">
      <coord axis="wght" value="3.2"/>
      <coord axis="wdth" value="1.3"/>
    </NamedInstance>

    <!-- Light Extended -->
    <NamedInstance flags="0x0" subfamilyNameID="299">
      <coord axis="wght" value="0.48"/>
      <coord axis="wdth" value="1.3"/>
    </NamedInstance>

    <!-- Black Condensed -->
    <NamedInstance flags="0x0" subfamilyNameID="300">
      <coord axis="wght" value="3.0"/>
      <coord axis="wdth" value="0.7"/>
    </NamedInstance>

    <!-- Light Condensed -->
    <NamedInstance flags="0x0" subfamilyNameID="301">
      <coord axis="wght" value="0.48"/>
      <coord axis="wdth" value="0.7"/>
    </NamedInstance>

    <!-- Bold -->
    <NamedInstance flags="0x0" subfamilyNameID="304">
      <coord axis="wght" value="1.95"/>
      <coord axis="wdth" value="1.0"/>
    </NamedInstance>
```

Things work OK for Light, Condensed or Extended, for example, but not for Light Extended. They work OK using instead the axes combination equivalent to Light Extended, namely

`\font="Skia:axis={wght=0.48,wdth=1.3}"`

**Comment by zauguin** [comment]
The issue tracker is not a good place for general usage questions.

**Comment by bgvoisin** [comment]
> On 12 Jul 2022, at 23:11, Marcel Krüger ***@***.***> wrote:
> 
> The issue tracker is not a good place for general usage questions.

Sorry for that.

Since I couldn't find a dedicated mailing list for luaotfload, I thought that maybe the issue tracker was the best way to communicate for questions specific to luaotfload.

Looking closer now, I see that README.md recommends the general lualatex-dev list. I'll be reposting my question to it.

Sorry again,

Bruno
