### ISSUE TITLE
Instance names containing spaces don't work in node mode

### ISSUE THREAD

**Issue by bgvoisin** [latex3/luaotfload#233]
This is linked to closed issue #231: for variable fonts, further investigation showed instance names with spaces work fine in harf mode but not in node mode. The corresponding axis values work fine in both modes.

Attached is a test file (plain LuaHBTeX) for the Fraunces font used in the luaotfload doc: the problem arises for Fraunces-Italic, whose most named instances have a space in their name.

The instances and equivalent axis definitions were obtained using ttx to get the fvar table for the fonts.

[Fraunces-Instace-Test.zip](https://github.com/latex3/luaotfload/files/9169645/Fraunces-Instace-Test.zip)

**Comment by zauguin** [comment]
This will be fixed in the next version. (It's already fixed in the `dev` branch) BTW you can avoid the issue in the meantime by removing the spaces from the instance key, so while e.g. `instance=Bold Italic` breaks, `instance=BoldItalic` works fine.

**Comment by bgvoisin** [comment]
Removing the spaces doesn't seem to fix the issue on my setup (MacTeX 2022). I get several "Warning (luaotfload): Unknown instance name ignored", and not the expected instance (this time for both node and harf modes).

[Fraunces-Instance-Test-Alt.zip](https://github.com/latex3/luaotfload/files/9169965/Fraunces-Instance-Test-Alt.zip)

**Comment by zauguin** [comment]
For `harf` you shouldn't remove the spaces (we might become more tolerant there later, but currently it's space sensitive) and `harf` is also the component generating the warnings.

Not sure why it would fail for `node` though, can you upload your log file?

**Comment by zauguin** [comment]
For `harf` you shouldn't remove the spaces, there they are important. (We might make `harf` more tolerant here later)

In `node` mode they are supposed to be ignored which had a bug. That can be worked around by removing the spaces, but that doesn't work if the broken version is already cached. Then you would have to remove the caches first (Normally under `$HOME/.texlive2022/texmf-var/luatex-cache/generic/fonts/streams/*`, but MacOS might vary)

**Comment by bgvoisin** [comment]
It's almost the same on the Mac, `$HOME/Library/texlive/2022/texmf-var/luatex-cache/generic/fonts/streams` (MacTeX sets `TEXMFVAR = ~/Library/texlive/2022/texmf-var` and similarly for `TEXMFCONFIG`).

Thanks, removing the caches did solve the matter. I had run `luaotfload-tool --update --force`, but didn't realize it only dealt with the name database, not the caches.

**Comment by FrankMittelbach** [comment]
> Thanks, removing the caches did solve the matter. I had run `luaotfload-tool --update --force`, but didn't realize it only dealt with the name database, not the caches

Wouldnt it make sense @zauguin that `--force` also clears the caches? Would be what I would also expect from forcing.

**Comment by u-fischer** [comment]
in view that recreating the caches of some fonts can take quite some time it would be better if `--force` wouldn't clear it by default. But there could be an explicit option e.g, `--clear-caches`, or `--reallyforce`

**Comment by FrankMittelbach** [comment]
I was wondering if I should request an additional option, but I thought that when you apply "force" you are prepared for a wait, but you expect force (like @bgvoisin) to mean force not partially force that needs additional options. But in either case, having an option that hides the system differences where those caches are when you want to clean them would be a good thing.

**Comment by zauguin** [comment]
Well, `-f` "forces" the database update (triggered by `-u`) which is completely independent from the cache and uses separate commands in `luaotfload-tool`. Given that the cache isn't generated from the update command, removing it when an update is forced seems odd.

There's also the issue that one usecases for updating the database is specifically to speed up further runs (e.g. when a fixed image is created) where removing the caches would be rather contra productive.

> But there could be an explicit option e.g, `--clear-caches`, or `--reallyforce`

`luaotfload-tool` allows to add multiple operations in the same commad, so you can already use `luaotfload-tool --update --force --caches=erase`.

**Comment by u-fischer** [comment]
> ` --caches=erase`  

citing the documentation is unfair ;-)

**Comment by FrankMittelbach** [comment]
> citing the documentation is unfair ;-)

so it is, especially when you go and say things like "it can be found here and there but not sure on OSX ..." which kind of suggests to me you had to reread your documentation too :-)
