### ISSUE TITLE
`dvisvgm` cannot find some OpenType font for display math when converting from DVI produced with `dvilualatex`

### ISSUE THREAD

**Issue by agrahn** [latex3/luaotfload#234]
After discussing this in the [tex.sx chat](https://chat.stackexchange.com/transcript/message/61674441#61674441), @u-fischer suggested to file the report here.

The font for display math is not found when converting `dvilualatex`-generated DVI to SVG with `dvisvgm`. For typesetting,

    dvilualatex input.tex
    dvisvgm --zoom=-1 --font-format=woff2 --bbox=papersize input.dvi

need to be run.

````latex
\documentclass[12pt]{article}

\DeclareSymbolFont{pureletters}{TU}{lmr}{\mddefault}{it}%
\DeclareMathSymbol{E}\mathalpha{pureletters}{"45}%

\begin{document}

% $E$   % <-- works, when enabled

\[ E \] % <-- `dvisvgm' produces warning and SVG contains replacement font

\end{document}
````

**Comment by zauguin** [comment]
Somewhat related to #176.
