### ISSUE TITLE
Documentation: example in section 7.2 "Combination" does not compile

### ISSUE THREAD

**Issue by daflipo** [latex3/luaotfload#235]
With an up to date TL2022, I get this error message:

This is LuaTeX, Version 1.15.0 (TeX Live 2022) 
 restricted system commands enabled.
(./test-plain.tex
(/usr/local/texlive/2022/texmf-dist/tex/luatex/luaotfload/luaotfload.sty
(/usr/local/texlive/2022/texmf-dist/tex/latex/base/ltluatex.tex))
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: Font "combo" not found.
luaotfload | resolve : sequence of 3 lookups yielded nothing appropriate.
! Font \onetwothree=combo: 1 -> 51; 2 -> 52, 0x30-0x39; 3 -> 53, 0x21*0x3f;  no
t loadable: metric data not found or bad.
<to be read again>

**Comment by u-fischer** [comment]
Don't you think that it matters what it is in your tex file?

**Comment by daflipo** [comment]
Le 01/09/2022 à 15:59, Ulrike Fischer a écrit :
> Don't you think that it matters what it is in your tex file?

As mentioned in the title, I just try to compile your example, not a 
personal file:

\def \feats {-tlig;-liga;mode=base;-kern}
\def \fileone {EBGaramond12-Italic.otf}
\def \filetwo {FreeMonoBoldOblique.otf}
\def \filethree {SourceSansPro-ExtraLight.otf}
\input luaotfload.sty
\font \one = file:\fileone :\feats
\font \two = file:\filetwo :\feats
\font \three = file:\filethree :\feats
\font \onetwothree = "combo: 1 -> \fontid \one ;
                            2 -> \fontid \two , 0x30-0x39;
                            3 -> \fontid \three , 0x21*0x3f;"

{\onetwothree \TeX —0123456789—?!}
\bye

I wonder why I get the following error
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: Font 
"combo" not found.
luaotfload | resolve : sequence of 3 lookups yielded nothing appropriate.
! Font \onetwothree=combo: 1 -> 51; 2 -> 52, 0x30-0x39; 3 -> 53, 
0x21*0x3f; not loadable: metric data not found or bad.

Am I missing something?
-- 
Daniel Flipo
