### ISSUE TITLE
Wrong glyph inserted with HarfBuzz renderer

### ISSUE THREAD

**Issue by fpom** [latex3/luaotfload#246]
I've reported [issue #579 to polyglossia](https://github.com/reutenauer/polyglossia/issues/579) and got suggested that it might interest you as well. When using `HarfBuzz` render instead of `Node`, `\symbol` may select the wrong glyph. As a minimal example, we have:

```latex
% !TeX TS-program = lualatex
\documentclass{article}
\usepackage{fontspec}
\newfontfamily{\mdih}{Material Design Icons Desktop}[Renderer=HarfBuzz]
\newfontfamily{\mdin}{Material Design Icons Desktop}[Renderer=Node]
\begin{document}
	{\mdih\symbol{"F0A27}}{\mdin\symbol{"F0A27}}
\end{document}
```

Which yields:
![Screenshot from 2023-02-23 14-53-54](https://user-images.githubusercontent.com/4525552/220927497-14e74e0c-65e2-487f-a121-1e0d98c6ef5b.png)
where the correct glyph is on the right. It might be a problem related to font loading hence this report. The font used in the example above is available [here](https://github.com/Templarian/MaterialDesign-Font).

**Comment by zauguin** [comment]
As far as I can tell it's the other way around: The left (HarfBuzz) one is `F0A27` (and therefore correct), while the right (Node) one is `F0A2E`.

That would be expected since the `node` mode does by design not support reliable selection of characters in the private use blocks. (see e.g. https://github.com/latex3/luaotfload/issues/185#issuecomment-838538340)

**Comment by khaledhosny** [comment]
> That would be expected since the `node` mode does by design not support reliable selection of characters in the private use blocks. (see e.g. [#185 (comment)](https://github.com/latex3/luaotfload/issues/185#issuecomment-838538340))

That is broken though, since private use means Unicode does not give it a meaning not that it is free for applications to reappropriate, PUA concept was borrowed from CJK encodings where it is often used for things like rare characters/personal names. https://www.unicode.org/faq/private_use.html

**Comment by jspitz** [comment]
> As far as I can tell it's the other way around: The left (HarfBuzz) one is `F0A27` (and therefore correct), while the right (Node) one is `F0A2E`.

You are right, as can be seen on the font's [cheat sheet](https://github.com/Templarian/MaterialDesign-Font/blob/master/cheatsheet.html).

**Comment by callegar** [comment]
I think this is the same as bug [185](https://github.com/latex3/luaotfload/issues/185)

**Comment by zauguin** [comment]
Right, it's kind of the opposite (since it's about the HarfBuzz renderer *not* having issue 185, but in any case it's not really a separate issue
