### ISSUE TITLE
OpenType features not recognized for all fonts in combo list

### ISSUE THREAD

**Issue by jasperhabicht** [latex3/luaotfload#248]
In the manual (2022-10-03 v3.23) on page 22 (7. Combining fonts, 7.2 Combinations) there is an example showing how to combine different fonts which are then selected according to their codepoints. 

The example shows that it should be possible to select font features for each of these fonts. However the following example shows that OpenType features are obviously not recognized except for the first font in the combo list. (This behaviour is also reported in the manual of the package `combofont` which seemingly relies on the mechanisms of the `luaotfload` package.)

```
\documentclass{article}
\usepackage{luaotfload}
\font \sourcesansproRA = {name:Source Serif Pro-Regular:mode=node;language=DFLT;+tlig} at 10pt
\font \sourcesansproRB = {name:Source Serif Pro-Regular:mode=node;language=DFLT;+tlig;+smcp} at 10pt
\font \sourcesansproRC = "combo: 1 -> \fontid \sourcesansproRA ; 2 -> \fontid \sourcesansproRB , 0x30-0x39; "
\font \sourcesansproRD = "combo: 1 -> \fontid \sourcesansproRB ; 2 -> \fontid \sourcesansproRA , 0x30-0x39; "

\newcommand{\alphabet}{ABCDefgh}
\newcommand{\digits}{0123456789}

\begin{document}

\sourcesansproRA
Source Serif Pro (without small caps): \par 
0123456789

\bigskip

\sourcesansproRB
Source Serif Pro (with small caps): \par 
0123456789

\bigskip

\sourcesansproRC
Source Serif Pro (with small caps only for U+0030 to U+0039): \par 
0123456789 --- not working

\bigskip

\sourcesansproRD
Source Serif Pro (with small caps except for U+0030 to U+0039): \par 
0123456789 --- not working

\end{document}
```

![image](https://user-images.githubusercontent.com/6378801/224477018-e3bdd159-3ca3-4cd2-8e0e-8fca02269318.png)

I would expect that OpenType features are recognized for all fonts in the combo list, since the example in the manual acutally selects features for each of the fonts used in the combi list.

**Comment by zauguin** [comment]
The example in the documentation doesn't enable any features, it disables them o avoid such issues since feature handling in `combo` fonts doesn't work. It also uses `base` fonts which work much better in that context.

Generally 1-to-1 substitution features (like the ones in your example) should work for all fonts as long as `mode=base` is used, while other features will apply the feature from the first font everywhere (which usually won't work).

We could document this, but I think we should just deprecate the whole mechanism and add a huge warning not to use it to the documentation.

**Comment by jasperhabicht** [comment]
> The example in the documentation doesn't enable any features, it disables them o avoid such issues since feature handling in `combo` fonts doesn't work. It also uses `base` fonts which work much better in that context.

You are indeed right in that the above code example works using `mode=base`. I think a short notice in the manual would be helpful. 

I think that the combo-font mechanism is a nice thing to have because it allows font replacement for specific codepoints, that is, not based on scripts or languages and without using a fallback which would somehow require the relevant glyphs are not contained in the other font.

**Comment by zauguin** [comment]
The problem with `combo:` is that it just uses some glyphs from another font without integrating it them correctly into the new font. As you saw font features break in various way. Them not being applied is one thing, but we also use features from a different font than the one the glyphs are from:
```
\documentclass{article}
\usepackage{luaotfload}
\font \serif = {name:lmroman10-regular.otf:mode=base;script=latn;language=DFLT} at 10pt
\font \sans = {name:lmsans10-regular.otf:mode=base;script=latn;language=DFLT} at 12pt
\font \combined = "combo: 1 -> \fontid \serif ; 2 -> \fontid \sans , 0x66*0x74; "

\begin{document}

\combined
Here all fs and ts are written in sans-serif and slightly bigger, but ligatures involving these characters like ff are not affected.

\end{document}
```
![image](https://user-images.githubusercontent.com/962229/224542601-ff24a4ea-c523-491e-bd5c-0e6eb9aa291c.png)

This is somewhat documented, but I can't imagine that it's ever the intended behavior. If we want to allow selecting individual characters from different fonts, then we should just extend the `fallback` system to be more configurable.
