### ISSUE TITLE
segmentation fault with Malayalam variable font

### ISSUE THREAD

**Issue by santhoshtr** [latex3/luaotfload#253]
When compiling a simple Malayalam tex document with lualtex I am getting segmentation fault.

Steps to reproduce.
1. Get the Tex and variable ttf file from this zip file and extract: https://thottingal.in/bugs/lualatex-issue.zip
2. Run `lualatex tiger.tex`
3. Observer segmentation fault

```
$ lualatex --version
This is LuaHBTeX, Version 1.15.0 (TeX Live 2022/Debian)
Development id: 7509
```

OS: Ubuntu 23.04

If used with a TeX file with completely latin content, lualatex works fine(Font supports latin too)

**Comment by zauguin** [comment]
This should be fixed on the `dev` branch.

**Comment by santhoshtr** [comment]
Thanks. I guess 14cdbc790583e219fe7956068b48f0f5182de59b was the fix.
