### ISSUE TITLE
add info on 'kerning' and 'ligature' callbacks

### ISSUE THREAD

**Issue by lemzwerg** [latex3/luaotfload#260]
'Kerning' and 'ligaturing' callbacks only have an effect on kerning and ligaturing, respectively, if 'luaotfload' is using `mode=base` for rendering.  Please add this to the documentation

See https://tug.org/pipermail/luatex/2023-July/007844.html for more; I've also filed https://github.com/latex3/latex2e/issues/1111 for the 'ltluatex' side.

**Comment by zauguin** [comment]
The formulation seems odd: The callbacks do have an effect (on what depends on how the callback is implemented), it's just that the default kerning and ligatures are applied elsewhere (at least some of them), so *disabling* kerning and ligatures by disabling the callback doesn't work. And even that depends on implementation details of the specific font configuration in use.

We could probably add a note along the line of:

> OpenType ligatures and kerning are not applied in the `ligaturing` and `kerning` callbacks but in a unified shaping pass. The `pre_shaping_filter` and `post_shaping_filter` callbacks are provided to allow hooking into before and after this pass.
>
> The specific time when extended features are applied is unspecified and might not be consistent.

**Comment by lemzwerg** [comment]
Sounds good, thanks!

**Comment by zauguin** [comment]
Done in https://github.com/latex3/luaotfload/commit/247a576d5d8ba48ec602a8233e3523928e7234b2
