### ISSUE TITLE
Arabic font  misaligned diacritics marks 

### ISSUE THREAD

**Issue by seloumi** [latex3/luaotfload#272]
## Brief outline of the bug

With the latest updates, a problem has appeared with positioning (overlap) of diacritics marks, we need to add `Renderer = HarfBuzz` option as font feature to get a correct result which was not required previously.

https://tex.stackexchange.com/q/705310/54817

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       
\documentclass{article}
\usepackage{fontspec}
\setmainfont[Script=Arabic]{Amiri}  
%\setmainfont[Script=Arabic,Renderer = HarfBuzz]{Amiri} % this give correct result

\textdir TRT \pardir TRT

\begin{document}

\Huge
السَّلام 

\end{document}
```

## Log file (required) and possibly PDF file  

[test6.pdf](https://github.com/latex3/latex2e/files/13731125/test6.pdf)
[test6.log](https://github.com/latex3/latex2e/files/13731126/test6.log)

**Comment by zauguin** [comment]
@seloumi I added an initial implementation of arabic reordering on the `dev` branch, it would be great if you could try it out and check if it renders arabic text correctly.

**Comment by seloumi** [comment]
Nothing changed, the problem remains the same :(

**Comment by zauguin** [comment]
@seloumi You get the same output with `luaotfload` installed from the current `dev` branch? That's weird. Can you upload your log file?

**Comment by seloumi** [comment]
[test6.log](https://github.com/latex3/luaotfload/files/13745821/test6.log)

**Comment by zauguin** [comment]
That log is not using the `dev` branch from `luaotfload`. Please run

```
git clone --branch=dev --depth=1 https://github.com/latex3/luaotfload.git luaotfload
cd luaotfload
l3build install
```
and then try again.

**Comment by seloumi** [comment]
I did what you said and I got the correct result, thanks for the guidance.

**Comment by zauguin** [comment]
Have you tried this with other arabic documents? Did it generally improve the output or where there still issues?

**Comment by seloumi** [comment]
I will try and let you know if any problems arise.

**Comment by seloumi** [comment]
I've tested texts with full diacritics marks and everything appears fine, thanks for the fix.
