### ISSUE TITLE
Characters with Bidi_Mirrored property are not mirrored

### ISSUE THREAD

**Issue by khaledhosny** [latex3/luaotfload#61]
Characters with `Bidi_Mirrored` property should be mirrored when text direction is RTL. OpenType spec describes [how character level mirroring and glyph level mirroring should be applied](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1#left-to-right-and-right-to-left-text).

For example, the following file should give `()` but it currently gives `)(`:

```tex
\input luaotfload.sty
\font\amiri="file:amiri-regular.ttf"
\amiri\textdir TRT ()
\bye
```

**Comment by zauguin** [comment]
@khaledhosny Do you know a font where at least one of the features `ltrm`, `ltra`, `rtlm` or `rtla` shares at least one lookup with another feature?

**Comment by khaledhosny** [comment]
No, but why do you need such font?

**Comment by zauguin** [comment]
@khaledhosny Beside the data file mess, replacing based on Bidi_Mirroring_Glyph is easy. So the interesting part is aplying `ltrm`, `ltra`, `rtlm` and `rtla` correctly. As far as I can tell the fontloader doesn't has the concept of enabling a feature only in one direction, but a specific lookup can react to the direction. So I would implement these by replacing the lookups of these features with modified lookups which only act in the right direction. Now if a font uses the same lookup for e.g. `ltra` and `calt` and `calt` is activated, the lookup should be applied independently of the direction. This is a case I would like to test.

**Comment by khaledhosny** [comment]
I think that is a case where the font loader is better fixed than worked around.

**Comment by zauguin** [comment]
@khaledhosny I do not see what you mean by fixing the font loader, the fontloader just uses a slightly different model where the direction is tracked in a single run instead of using multiple directional runs.

**Comment by khaledhosny** [comment]
I don’t get what you mean by multiple runs. The lookups are collected based on the script, language and direction, then applied.

**Comment by zauguin** [comment]
@khaledhosny Right, this requires collecting lookups based on direction, basically requiring separate runs for each direction, while the fontloader only collects lookups based on script and language, therefore combining the shaping of both directions without requiring additional passes over the nodes. Of course, this moves the responsibility for handling the direction from the lookup collection to the "lookup execution" step.

Anyway, could you test the implementation in the `mirror` branch?

**Comment by khaledhosny** [comment]
I can’t test right now, feel free merge the fix if its looks good to you.

**Comment by u-fischer** [comment]
Seems to work as expected in bidi-dev.
