### ISSUE TITLE
Set face index when loading TTC files

### ISSUE THREAD

**Issue by khaledhosny** [latex3/luaotfload#66]
In LuaTeX there is no way to directly set face index (or subfont in luaotfload nomenclature) for font collection (e.g. TTC) files, and instead the engine uses the `psname` of the font to search for its index. HarfTeX just removed the `psname` hack since it is both unreliable (as the `psname` set on the font structure does not neccasirily match what is in the font file, e.g. after [sanitization](https://github.com/khaledhosny/harf/issues/38)), and depends on the internal FontForge code which was removed.

HarfTeX instead has an `index` key in the font structure that should be set, otherwise TTC fonts will always use the face at index 0.

**Comment by khaledhosny** [comment]
#67 was closed but not this issue, is it fixed now or not yet?

**Comment by khaledhosny** [comment]
For compatibility with LuaTeX I’m going to revert the change mentioned above, so setting the index is no longer required, though I still think it is more robust to be explicit here and not rely on heuristics.

**Comment by u-fischer** [comment]
Hm. Good question. I don't remember to have closed #67 ;-).  And the patch is not in the current newest branch -- I had left if open because of the unclear 1-or-0-based index and the open question of the engine lualatex will be based in tl2020. I will reopen the pull request.

**Comment by khaledhosny** [comment]
HarfTeX is no more.

**Comment by zauguin** [comment]
A slightly different variant of this got becomes part of `luahbtex`, so let's reopen.

**Comment by zauguin** [comment]
Done in https://github.com/latex3/luaotfload/commit/79c5e5049ff97ae67ef3ef37b54ff05d619a08e5.
