### ISSUE TITLE
Ligatures in ttc not displaying

### ISSUE THREAD

**Issue by solisoc** [latex3/luaotfload#74]
Hello,

@u-fischer has pointed me here to open an issue I originally raised on tex.stackexchange.com: [LuaLaTeX not outputting ligatures in Helvetica Neue TrueType Collection](https://tex.stackexchange.com/questions/501715/lualatex-not-outputting-ligatures-in-helvetica-neue-truetype-collection). As a novice programmer and first-time user of GitHub, I'm not sure exactly what else I should provide in reporting this issue, but I'm happy to follow any requests on that score. Although I did not make it clear in that question, I am using macOS Mojave.

**Comment by zauguin** [comment]
@solisoc Please upload files named something with `helvetica` from `~/Library/texlive/2019/texmf-var/luatex-cache/generic/fonts/otl`.

**Comment by solisoc** [comment]
[helvetica.zip](https://github.com/latex3/luaotfload/files/3563434/helvetica.zip)
Apologies for the delay. In the above archive are all the files in that folder which fit that description.

**Comment by zauguin** [comment]
The problem with the font in question is that the ligatures are not actually represented as OpenType ligatures but as AAT liagtures. AAT is not supported by the ConTeXt fontloader but automatically handled by HarfBuzz, so the ligatures should work in lualatex-dev if the fontspec option `Renderer=Harfbuzz` is added.

**Comment by zauguin** [comment]
Closing this here. It works with `mode=harf` is not really in scope for the `mode=node` fontloader which "only" deals with OpenType.
