### ISSUE TITLE
bidi-dev output of bidi-pr83.lvt correct?

### ISSUE THREAD

**Issue by u-fischer** [latex3/luaotfload#92]
I wonder if my output of the bidi-pr83.lvt test file is correct. 

The  £49 against 39£ looks a bit odd, but there could be hidden direction chars .involved...  

![image](https://user-images.githubusercontent.com/4047173/63694924-cb2c6c80-c817-11e9-9eda-49a97f8e57c2.png)

**Comment by zauguin** [comment]
It's compatible with LibreOffice output, so it should be fine. There are no hidden direction chars but according to the [Unicode bidirectional algorithm, rule W2,](http://unicode.org/reports/tr9/#W2) the characters prior to the number decide if the number is arabic or european(Which ends up influencing the position of the £). 
To figure out which character logically precedes the number, the easiest option I know is looking at the test with a editor which does not support bidi:
![image](https://user-images.githubusercontent.com/962229/63696811-cec1f280-c81b-11e9-8aab-bcb00ea6f880.png)
So `39£` is an european number while `49£` is an arabic number and therefore becomes `£49`.

**Comment by jbezos** [comment]
@zauguin If you are using Notepad++ the following may interest you. I had exactly the same problem, so I wrote my own solution, available here:

https://github.com/jbezos/personal-npp-luascript

With one of the functions (namely, `showChars`) I can select a text and then a pop-up shows the hex values and the chars as ordered in the file. I think I couldn't have written the bidi algorithm without it. By the way, my tests with `babel` mostly works, which is good news for me :-).

Note symbols with numbers actually depend on 3 cases, not 2: Arabic letter (AL), right (R, Hebrew) and European. For example, with AL it's %123, but with R is 123%.

**Comment by u-fischer** [comment]
@zauguin thanks. Actually my editor shows the "non bidi" output, but I wasn't sure if I should trust it. 

It looks as if travis is happy again ...
