### ISSUE TITLE
Lualatex + fontconfig cannot find the italic, bold, bolditalic versions of XITS font, xelatex can

### ISSUE THREAD

**Issue by callegar** [latex3/luaotfload#93]
On my machine

     \setmainfont{XITS}

is not enough to let fontspec find the italic, bold and bold-italic versions of XITS when using luatex and luaotfload. I get:

```
Package fontspec Info: Could not resolve font "XITS/BI" (it probably doesn't
(fontspec)             exist).


Package fontspec Info: Could not resolve font "XITS/B" (it probably doesn't
(fontspec)             exist).


Package fontspec Info: Could not resolve font "XITS/I" (it probably doesn't
(fontspec)             exist).
```

however, the thing works just fine in xelatex and fc-match can find the italic, bold etc versions of XITS just fine. For instance:

```
fc-match XITS:italic
XITS-Italic.otf: "XITS" "Italic"
```

To make things work, I need to explicitly indicate the fonts to use as in:

    \setmainfont{XITS}[ItalicFont=XITS-Italic,
    BoldFont=XITS-Bold, BoldItalicFont=XITS-BoldItalic]

which seems redundant and is not needed for any other fonts. For instance the Italic, bold, bold-italic versions of Times New Roman, TeX Gyre Termes, STIX Two Text are found automatically.

**Comment by zauguin** [comment]
@callegar Thank you for the report. I have some trouble reproducing your problem, when I for example try

```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{XITS}
\begin{document}
A \bfseries very \itshape nice \mdseries world.
\end{document}
```
everything works correctly and all fonts are found. Which system are you using? Is you luaotfload up to date?

It might be a problem with the font cache. Could you try if the problem persists after you ran
```
luaotfload-tool -u -f
```

?

**Comment by callegar** [comment]
@zauguin,

thanks, that did the trick. In the recent past the XITS fonts were updated on my system via tlmgr and I was expecting the upgrade to do all the work for me, didn't know about the need to re-cache the fonts. Sorry for the noise.

Is the caching per-user or per-system? Namely, should every user on the system run the cache update or having only one do it is enough?
