### ISSUE TITLE
Merging in the harf code?

### ISSUE THREAD

**Issue by khaledhosny** [latex3/luaotfload#97]
Would luaotfload maintainers be interested in merging in the [harf](https://github.com/khaledhosny/harf) code (and effectively taking over its maintenance)? I think the HarfBuzz shaping would benefit from tighter (and official) integration with luaotfload.

**Comment by u-fischer** [comment]
@khaledhosny  Yes, we are interested. I quite agree that the harfbuzz shaping should be a properly part of luaotfload and lualatex. Could you please clarify the license of the code?

**Comment by khaledhosny** [comment]
Whatever the license of luaotfload is OK. It seems luaotfload is GPL licensed which is rather good.

**Comment by khaledhosny** [comment]
What would be the next steps here?

**Comment by khaledhosny** [comment]
I added license file, file headers and few cleanups to the repository that hopefully make integrating with luaotfload a bit simpler.

**Comment by zauguin** [comment]
@khaledhosny Sorry that I forgot to answer. I am currently working on integrating it in the `harf-dev` branch.
The current step is to reduce duplicate functionality as much as possible. Therefore I tried to change the code to use the fontloader's plugin mechanism to avoid separate callbacks as much as possible and allow more or less uniform handling.
Currently I am working on the color code: I would want to avoid a situation where we have two competing coloring systems so we need to combine them.

**Comment by khaledhosny** [comment]
Originally I wanted to keep the code independent from luaotfload, but since that is not and issue in this situation, I agree a few thangs can be made more integrated. There is also the code for handling temporary image files, IIRC luaotfload had some helper functions to handle and cache such temporary files but I didn’t use it.

**Comment by zauguin** [comment]
I pushed a `harfnode-dev` branch which is a version based on traversing node lists and less indices. (The main motivation was to keep better track of nodes to avoid leaking them. Also it looks more natural IMO.
So we are back at the old problems, mostly coloring and PNG handling.

My main problem with coloring is that I get the impression that a proper system would basically end up reimplementing `luacolor` and proper transparency support would reimplement the `transparency` package, without being compatible with this package. Maybe we should move both, coloring and PNG handling, into (virtual) glyphs or do the replacement in pre_linebreak_filter.

**Comment by u-fischer** [comment]
@zauguin transparency (and probably color too) is related to the pdfresource project, and I have there also a reimplementation of the `transparent`  package. If there is something that is currently missing in the pdfresources we should/can coordinate this.

**Comment by zauguin** [comment]
PNG handling and layered glyphs are now handled through virtual characters, which e.g. allows them to appear in discretionaries, avoids separate codepaths etc. Also this made it possible to remove the entire color infrastructure here and use the color system from luaotfload instead.

**Comment by zauguin** [comment]
@u-fischer The changes I really wanted to get in before merging it are ready, so now it mostly needs testing. The I think we should try to merge it soon, it waited long enough. You probably saw that I created a release for easier testing.

Are there any important changes you want to see before merging this into dev?

**Comment by u-fischer** [comment]
@zauguin I'm quite in favor to reduce the number of branches and to clean up a bit. (Only that I just wrote Norbert that he can use the harfnode-dev branch, so this should be corrected ;-( ). 

But I think we need some documentation for the harf code, and also some test files.

**Comment by khaledhosny** [comment]
Thanks @zauguin for integrating and improving the code!
