### ISSUE TITLE
A problem when I try to caching in the first time.

### ISSUE THREAD

**Issue by Steve-Cheung-emct** [latex3/luaotfload#99]
windows 10, texlive 2019 
luaotfload version 52290 (51290 as well as the same)

Please help me. Thank you very much.

_____________________________________________________
C:\Windows\system32> luaotfload-tool -f -u -v
luaotfload | db : Updating the font names database forcefully.
luaotfload | db : Scanning TEXMF and $OSFONTDIR for fonts...
luaotfload | db : Scanning system fonts...
luaotfload | db : Scanning 8835 collected font files ...
C:\texlive\2019\bin\win32\runscript.tlu:927: ...texmf-dist/tex/luatex/luaotfload/luaotfload-database.lua:2284: attempt to perform arithmetic on a nil value (local 'len')

C:\Windows\system32>

**Comment by u-fischer** [comment]
please increase the verbosity (`-vvvv` or more) to find out which font is triggering the error).

**Comment by Steve-Cheung-emct** [comment]
Thank you very much.

After I do this below, successed at last.
https://github.com/latex3/luaotfload/commit/d8139feb5dcf29e0c8c3afb71c7e29f7c545a2be

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
luaotfload | cache : Lookup cache saved.
luaotfload | cache : Lookup cache emptied.
luaotfload | db : Fonts in the database: 2792
luaotfload | util : Task completed successfully.
